# this is *.properties file.
# file encoding: ISO-8859

sonar.coverage.exclusions=tools/**/*,src/test/**/*

sonar.sourceEncoding=UTF-8

sonar.sources=.

sonar.exclusions=build/**/*,externals/**/*,tools/HeaderMake/*,tools/ppa_stub/*,src/*/resources/**/*,src/test/**/test-*.cpp,tests*-*.xml

sonar.python.version=3
