//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChmSourceConverter.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>.html</string>\r\n  <string>.css</string>\r\n  <string>.js</string>\r\n</ArrayOf" +
            "String>")]
        public global::System.Collections.Specialized.StringCollection TargetExtensions {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["TargetExtensions"]));
            }
            set {
                this["TargetExtensions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("&#{0};")]
        public string EscapingFormat {
            get {
                return ((string)(this["EscapingFormat"]));
            }
            set {
                this["EscapingFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UTF-8")]
        public string InputEncoding {
            get {
                return ((string)(this["InputEncoding"]));
            }
            set {
                this["InputEncoding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Shift_JIS")]
        public string OutputEncoding {
            get {
                return ((string)(this["OutputEncoding"]));
            }
            set {
                this["OutputEncoding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(<meta http-equiv=\"Content-type\" content=\"text/html; charset=)UTF-8(\" */?>)")]
        public string ReplacePattern {
            get {
                return ((string)(this["ReplacePattern"]));
            }
            set {
                this["ReplacePattern"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1024")]
        public int MaxDegreeOfParallelism {
            get {
                return ((int)(this["MaxDegreeOfParallelism"]));
            }
            set {
                this["MaxDegreeOfParallelism"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1024")]
        public int OutputBufferSize {
            get {
                return ((int)(this["OutputBufferSize"]));
            }
            set {
                this["OutputBufferSize"] = value;
            }
        }
    }
}
