/*!	@file

	@author Project Sakura-Editor
*/
/*
	Copyright (C) 2007-2008, kobake
	Copyright (C) 2009, rastiv


	This software is provided 'as-is', without any express or implied
	warranty. In no event will the authors be held liable for any damages
	arising from the use of this software.

	Permission is granted to anyone to use this software for any purpose,
	including commercial applications, and to alter it and redistribute it
	freely, subject to the following restrictions:

		1. The origin of this software must not be misrepresented;
		   you must not claim that you wrote the original software.
		   If you use this software in a product, an acknowledgment
		   in the product documentation would be appreciated but is
		   not required.

		2. Altered source versions must be plainly marked as such,
		   and must not be misrepresented as being the original software.

		3. This notice may not be removed or altered from any source
		   distribution.
*/

/*
	++ 概要 ++

	define 定数定義ヘッダを生成するためのモノ

	++ 使用方法 ++

	usage() を参照
*/

#include <stdio.h>

int usage(){
	printf(
		"\nUsage: HeaderMake <OutputFile.h>\n"
		"\n"
		"  Argument parameters\n"
		"    OutputFile          : Output .h file path\n"
	);
	return 1;
}

int main(int argc, char* argv[])
{
	if (argc <= 1) {
		return usage();
	}

	FILE *out;
	auto ret = fopen_s( &out, argv[ 1 ], "w" );
	if( out == NULL ){
		printf( "can't open file: %s\n", argv[ 1 ] );
	}
	
	fprintf(out,
		"#ifndef SAKURA_HEADERMAKE_98B26AB2_D5C9_4884_8D15_D1F3A2936253_H_\n"
		"#define SAKURA_HEADERMAKE_98B26AB2_D5C9_4884_8D15_D1F3A2936253_H_\n"
		"\n"
	);	// インクルードガードを挿入（define 用）
	
	fprintf(out,
		"// This file is generated by HeaderMake with Funccode_x.h.\n"
		"// Don't edit this file manually.\n\n"
	);
	
	#define print_def( id, val )	fprintf( out, "#define %s %s\n", #id , #val )
	
	#define DEF_COMMAND(   id, val )													print_def( id, val );
	#define DEF_MACROCMD(  id, val, name, param0, param1, param2, param3, ret, ext )	print_def( id, val );
	#define DEF_MACROFUNC( id, val, name, param0, param1, param2, param3, ret, ext )	print_def( id, val );
	#define DEF_MACROCMD2( id,      name, param0, param1, param2, param3, ret, ext )
	#define DEF_MACROFUNC2(id,      name, param0, param1, param2, param3, ret, ext )
	
	#include "../sakura_core/Funccode_x.h"
	
	fprintf(out,
		"\n"
		"#endif /* SAKURA_HEADERMAKE_98B26AB2_D5C9_4884_8D15_D1F3A2936253_H_ */\n"
		"/*[EOF]*/\n"
	);	// インクルードガード終了（define 用）

	//後始末
	fclose(out);

	return 0;
}

