//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by sakura_rc.rc
//
#define IDOK2                           3
#define IDC_BUTTON_PRINTERSELECT        3
#define IDR_MENU1                       102
#define IDD_PROP1P1                     107
#define IDD_FIND                        109
#define IDD_PROP_FILE                   110
#define IDR_TRAYMENU_L                  113
#define IDD_ABOUT                       115
#define IDD_JUMP                        118
#define IDD_FUNCLIST                    122
#define IDD_GREP                        132
#define IDD_GREPRUNNING                 134
#define IDD_REPLACE                     137
#define IDD_TYPELIST                    147
#define IDD_PROPERTY_FILE               152
#define IDD_PROP_KEYWORD                153
#define IDD_INPUT1                      154
#define IDD_REPLACERUNNING              160
#define IDD_COMPARE                     168
#define IDD_PRINTPREVIEWBAR             170
#define IDD_PRINTSETTING                174
#define IDD_EXITING                     175
#define IDD_DEBUG                       177
#define IDD_EXEC                        182
#define IDD_HOKAN                       186
#define IDD_EXECCMD_TEST                188
#define IDD_EXECRUNNING                 191
#define IDD_PRINTING                    192
//#define IDD_PRINTPAGE                   193
#define IDB_MYTOOL                      200
#define IDB_PRINTER                     203
#define IDD_PROP_MACRO                  217
#define IDD_PROP_REGEX                  219
#define IDC_CURSOR_COPYARROW            220
#define IDC_CURSOR_HAND                 221
#define IDC_CURSOR_MOVEARROW            222
#define IDC_CURSOR_RVARROW              223
#define IDD_FILEUPDATEQUERY             225
#define IDD_PROP_FNAME                  226
#define IDD_FAVORITE                    227
#define IDD_TAGJUMPLIST                 228
#define IDD_TAG_MAKE                    229
#define IDI_ICON_STD                    230
#define IDI_ICON_DEBUG                  231
#define IDI_ICON_GREP                   240
#define IDC_CURSOR_ISEARCH_F            241
#define IDC_CURSOR_ISEARCH_B            242
#define IDD_DIALOG_KEYWORD_SELECT       243
#define IDD_SAMECOLOR                   244
#define IDC_CURSOR_TAB_LEFT             245
#define IDC_CURSOR_TAB_RIGHT            246
#define IDC_CURSOR_TAB_SEPARATE         247
#define IDC_CURSOR_TAB_JOIN             248
#define IDC_HIDE                        1000
#define IDC_CHK_LOHICASE                1006
#define IDC_CHECK_INDENT                1009
#define IDC_CHK_REGULAREXP              1010
#define IDC_COMBO_INDENTLAYOUT          1010
#define IDC_CHECK_INDENT_WSPACE         1011
#define IDC_CHECK_STOPS_BOTH_ENDS_WHEN_SEARCH_WORD 1012
#define IDC_CHECK_GTJW_RETURN           1013
#define IDC_CHECK_STOPS_BOTH_ENDS_WHEN_SEARCH_PARAGRAPH 1013
#define IDC_CHECK_RTRIM_PREVLINE        1013
#define IDC_CHECK_FREECARET             1014
#define IDC_BUTTON1                     1015
#define IDC_BUTTON_CLEAR_MRU_FOLDER     1016
#define IDC_BUTTON_RELEASE              1016
#define IDC_COMBO_TEXT                  1021
#define IDC_COMBO_TEXT2                 1022
#define IDC_CHECK_GTJW_LDBLCLK          1023
#define IDC_EDIT_MAXLINELEN             1029
#define IDC_EDIT_CHARSPACE              1031
#define IDC_SPIN_MAXLINELEN             1034
#define IDC_SPIN_CHARSPACE              1035
#define IDC_EDIT_LINESPACE              1037
#define IDC_SPIN_LINESPACE              1038
#define IDC_SPIN_REPEATEDSCROLLLINENUM  1039
#define IDC_EDIT_TABVIEWSTRING          1039
#define IDC_SPIN_TABSPACE               1040
#define IDC_EDIT_TABSPACE               1050
#define IDC_BUTTON_TEXTCOLOR            1056
#define IDC_BUTTON_BACKCOLOR            1060
#define IDC_STATIC_JRE32VER             1065
#define IDC_CHECK_EXCVLUSIVE_NO         1069
#define IDC_CHECK_EXCVLUSIVE_READWRITE  1070
#define IDC_CHECK_EXCVLUSIVE_WRITE      1071
#define IDC_CHECK_NOMOVE_ACTIVATE_BY_MOUSE      1072
#define IDC_EDIT_LINENUM                1074
#define IDC_CHECK_BACKUP                1076
#define IDC_CHECK_EXITCONFIRM           1076
#define IDC_CHECK_PLSQL                 1076
#define IDC_CHECK_SHIFT                 1076
#define IDC_CHK_FROMTHISTEXT            1076
#define IDC_CHECK_TOOLBARISFLAT         1076
#define IDC_CHECK_RELOADWHENEXECUTE     1076
#define IDC_CHECK_DOCICON               1076
#define IDC_CHECK_LCPOS2                1077
#define IDC_CHECK_SplitterWndHScroll    1077
#define IDC_RADIO_BACKUP_TYPE1          1078
#define IDC_RADIO_OUTPUTMARKED          1078
#define IDC_RADIO_ALLAREA               1078
#define IDC_RADIO_CARETTYPE1            1078
#define IDC_RADIO_nRulerType_1          1078
#define IDC_CHECK_LCPOS3                1078
#define IDC_RADIO_BACKUP_TYPE2          1079
#define IDC_RADIO_FUNCKEYWND_PLACE2     1079
#define IDC_CHECK_BACKUP_YEAR           1080
#define IDC_CHECK_ALT                   1080
#define IDC_CHECK_DispTabIcon           1080
#define IDC_CHECK_BACKUP_HOUR           1081
#define IDC_CHECK_BACKUP_MIN            1082
#define IDC_CHECK_BACKUP_SEC            1083
#define IDC_CHECK_BACKUPDIALOG          1084
#define IDC_CHECK_BACKUPFOLDER          1085
#define IDC_CHECK_UNDERLINE             1085
#define IDC_EDIT1                       1086
#define IDC_EDIT_BACKUPFOLDER           1086
#define IDC_EDIT_EXTHELP1               1086
#define IDC_EDIT_PLSQL_E1               1086
#define IDC_EDIT_BLOCKCOMMENT_FROM      1086
#define IDC_EDIT_TYPENAME               1086
#define IDC_BUTTON_BACKUP_FOLDER_REF    1087
#define IDC_BUTTON_REPALCE              1087
#define IDC_BUTTON_DELETE               1087
#define IDC_BUTTON_DELKEYWORD           1087
#define IDC_EDIT_EXTHTMLHELP            1087
#define IDC_EDIT_TFORM                  1087
#define IDC_EDIT_BLOCKCOMMENT_FROM2     1087
#define IDC_EDIT_FNAME_TO               1087
#define IDC_CHECK_BACKUP_MONTH          1088
#define IDC_BUTTON_INSERTSEPARATOR      1088
#define IDC_EDIT_KEYWORDHELPFILE        1088
#define IDC_BUTTON_ZOOMUP               1088
#define IDC_EDIT_MIGEMO_DLL             1088
#define IDC_CHECK_BACKUP_DAY            1089
#define IDC_BUTTON_KEYWORDHELPFILE_REF  1089
#define IDC_BUTTON_INSERTWRAP           1089
#define IDC_EDIT_MIGEMO_DICT            1089
#define IDC_RADIO_BACKUP_TYPE3          1090
#define IDC_CHECK_AUTOSAVE              1091
#define IDC_CHECK_BACKUP_DUSTBOX        1091
#define IDC_LIST1                       1092
#define IDC_CHECK_DispTOOLBAR           1092
#define IDC_EDIT_AUTOBACKUP_INTERVAL    1092
#define IDC_BUTTON_OPENHELP1            1096
#define IDC_BUTTON_OPENEXTHTMLHELP      1097
#define IDC_EDIT_REPEATEDSCROLLLINENUM  1098
#define IDC_BUTTON_KEYWORDHELPFONT      1098
#define IDC_BUTTON_HELP                 1099
#define IDC_BUTTON_OPENMDLL             1099
#define IDC_BUTTON_OPENHELP3            1100
#define IDC_BUTTON_OPENMDICT            1100
#define IDC_EDIT_TO                     1105
#define IDC_EDIT_BLOCKCOMMENT_TO        1109
#define IDC_EDIT_TYPEEXTS               1109
#define IDC_EDIT_MARGINTY               1109
#define IDC_EDIT_nRulerBottomSpace      1109
#define IDC_EDIT_LINECOMMENT            1110
#define IDC_EDIT_INDENTCHARS            1110
#define IDC_EDIT_MAX_MRU_FOLDER         1110
#define IDC_EDIT_MARGINBY               1110
#define IDC_EDIT_nLineNumberRightSpace  1110
#define IDC_EDIT_LINECOMMENT2           1111
#define IDC_EDIT_MARGINLX               1111
#define IDC_LIST_FUNC                   1112
#define IDC_EDIT_MARGINRX               1112
#define IDC_EDIT_BLOCKCOMMENT_TO2       1112
#define IDC_COMBO_FUNCKIND              1113
#define IDC_EDIT_DANSPACE               1113
#define IDC_EDIT_LINECOMMENT3           1113
#define IDC_LIST_KEY                    1114
#define IDC_CHECK_CTRL                  1115
#define IDC_CHECK_ADDCRLFWHENCOPY       1116
#define IDC_COMBO_FILE                  1118
#define IDC_COMBO_nSortType             1118
#define IDC_COMBO_FOLDER                1119
#define IDC_STATIC_STC32                1119
#define IDC_COMBO_SETTINGNAME           1119
#define IDC_COMBO_PAPER                 1120
#define IDC_BUTTON_FOLDER               1121
#define IDC_CHK_SUBFOLDER               1122
#define IDC_STATIC_CURPATH              1123
#define IDC_CHK_DEFAULTFOLDER           1124
#define IDC_STATIC_HITCOUNT             1125
#define IDC_EDIT_VER                    1126
#define IDC_LIST_ASSIGNEDKEYS           1129
#define IDC_STATIC_MSG                  1130
#define IDC_RADIO_OUTPUTLINE            1132
#define IDC_RADIO_SELECTEDAREA          1133
#define IDC_BUTTON_REPALCEALL           1134
#define IDC_BUTTON_SEARCHPREV           1135
#define IDC_CHECK_CONSECUTIVEALL        1136
#define IDC_BUTTON_SEARCHNEXT           1137
#define IDC_LIST_RES                    1138
#define IDC_BUTTON_SETMARK              1138
#define IDC_TREE1                       1140
#define IDC_BUTTON_ADD                  1141
#define IDC_BUTTON_INSERT               1142
#define IDC_BUTTON_REGEX_INS            1142
#define IDC_BUTTON_UP                   1143
#define IDC_BUTTON_DOWN                 1144
#define IDC_BUTTON_SAMEBKCOLOR          1144
#define IDC_CHECK_REPEATEDSCROLLSMOOTH  1145
#define IDC_BUTTON_SAMETEXTCOLOR        1145
#define IDC_COMBO_CODE                  1146
#define IDC_RADIO_CARETTYPE0            1147
#define IDC_COMBO_EOL                   1147
#define IDC_BUTTON_COPY                 1149
#define IDC_RADIO_ESCAPETYPE_1          1150
#define IDC_RADIO_ESCAPETYPE_2          1151
#define IDC_LIST_TYPES                  1153
#define IDC_RADIO_OUTPUTSTYLE1          1158
#define IDC_RADIO_nRulerType_0          1158
#define IDC_COMBO_PLSQLBLOCKS           1164
#define IDC_COMBO_MRU                   1167
#define IDC_CHECK_KEYWORDCASE           1168
#define IDC_COMBO_OPENFOLDER            1169
#define IDC_BUTTON_ADDKEYWORD           1170
#define IDC_BUTTON_IMPORT               1171
#define IDC_BUTTON_EXPORT               1173
#define IDC_BUTTON_ADDSET               1176
#define IDC_BUTTON_EDITKEYWORD          1177
#define IDC_BUTTON_DELSET               1178
#define IDC_COMBO_SET                   1179
#define IDC_COMBO_SET2                  1180
#define IDC_LIST_KEYWORD                1181
#define IDC_SPIN_MAX_MRU_FILE           1184
#define IDC_SPIN_MAX_MRU_FOLDER         1185
#define IDC_SPIN_nDropFileNumMax        1185
#define IDC_SPIN_nRulerBottomSpace      1185
#define IDC_EDIT_MAX_MRU_FILE           1186
#define IDC_SPIN_PLSQL_E1               1186
#define IDC_SPIN_LCColNum2              1186
#define IDC_SPIN_nLineNumberRightSpace  1186
#define IDC_BUTTON_CLEAR_MRU_FILE       1187
#define IDC_SPIN_LCColNum3              1187
#define IDC_COMBO_MENU                  1188
#define IDC_RADIO_FUNCKEYWND_PLACE1     1190
#define IDC_CHECK_DispFUNCKEYWND        1191
#define IDC_CHECK_NOTIFYNOTFOUND        1192
#define IDC_EDIT_MIDASHIKIGOU           1193
#define IDC_EDIT_INYOUKIGOU             1194
#define IDC_PROGRESS_REPLACE            1195
#define IDC_STATIC_KENSUU               1197
#define IDC_STATIC_MYICON               1198
#define IDC_EDIT_HOKANFILE              1201
#define IDC_BUTTON_HOKANFILE_REF        1203
//#define IDC_STATIC_UPDATE               1204
#define IDC_LIST_COLORS                 1211
#define IDC_CHECK_DISP                  1212
#define IDC_CHECK_FAT                   1213
#define IDC_RADIO_LINENUM_LAYOUT        1214
#define IDC_RADIO_LINENUM_CRLF          1215
#define IDC_STATIC_HAIKEI               1216
#define IDC_COMBO_CHARSET               1217
#define IDC_RADIO_LINETERMTYPE2         1218
#define IDC_EDIT_LINETERMCHAR           1220
#define IDC_RADIO_LINETERMTYPE0         1221
#define IDC_RADIO_LINETERMTYPE1         1222
#define IDC_LIST_FILES                  1223
#define IDC_STATIC_COMPARESRC           1224
#define IDC_CHECK_HOKANLOHICASE         1225
#define IDC_BUTTON_NEXTPAGE             1227
#define IDC_BUTTON_ZOOMDOWN             1228
#define IDC_BUTTON_PRINTSETTING         1232
#define IDC_EDIT_LINECOMMENTPOS         1234
#define IDC_BUTTON_PREVPAGE             1235
#define IDC_EDIT_LINECOMMENTPOS2        1235
#define IDC_SPIN_MARGINTY               1236
#define IDC_EDIT_LINECOMMENTPOS3        1236
#define IDC_SPIN_MARGINBY               1237
#define IDC_SPIN_MARGINLX               1238
#define IDC_SPIN_MARGINRX               1239
#define IDC_SPIN_FONTWIDTH              1241
#define IDC_SPIN_DANSUU                 1242
#define IDC_EDIT_FOOT1                  1243
#define IDC_COMBO_FONT_HAN              1244
#define IDC_COMBO_FONT_ZEN              1245
#define IDC_SPIN_DANSPACE               1247
#define IDC_EDIT_FONTWIDTH              1259
#define IDC_EDIT_DANSUU                 1260
#define IDC_CHECK_WORDWRAP              1261
#define IDC_CHECK_LINENUMBER            1262
#define IDC_CHECK_KINSOKUHEAD           1262
#define IDC_BUTTON_EDITSETTINGNAME      1263
#define IDC_CHECK_KINSOKUTAIL           1263
#define IDC_STATIC_PAGENUM              1264
#define IDC_CHECK_PS_KINSOKUHEAD        1264
#define IDC_CHECK_KINSOKURET            1264
#define IDC_STATIC_ZOOM                 1265
#define IDC_CHECK_PS_KINSOKUTAIL        1265
#define IDC_CHECK_KINSOKUKUTO           1265
#define IDC_CHECK_PS_KINSOKURET         1266
#define IDC_CHECK_PS_KINSOKUKUTO        1267
#define IDC_EDIT_HEAD1                  1270
#define IDC_STATIC_PRNDEV               1271
#define IDC_STATIC_PAPER                1272
#define IDC_EDIT_KEYSFUNC               1273
#define IDC_BUTTON_ASSIGN               1274
#define IDC_EDIT_HEAD2                  1275
#define IDC_EDIT_HEAD3                  1276
#define IDC_BUTTON_CURRENTFOLDER        1277
#define IDC_EDIT_DEBUG                  1278
#define IDC_EDIT_FOOT2                  1278
#define IDC_CHECK_USETRAYICON           1279
#define IDC_EDIT_FOOT3                  1279
#define IDC_CHECK_STAYTASKTRAY          1280
#define IDC_CHECK_DispSTATUSBAR         1281
#define IDC_RADIO_OUTPUTSTYLE2          1282
#define IDC_CHECK_DispTabWnd            1282
#define IDC_STATIC_ENABLECOLMNS         1283
#define IDC_CHECK_MultiWin              1283
#define IDC_STATIC_ENABLELINES          1284
#define IDC_HOTKEY_TRAYMENU             1286
#define IDC_CHECK_ENABLEUNMODIFIEDOVERWRITE 1287
#define IDC_CHECK_DRAGDROP              1289
#define IDC_CHECK_DROPSOURCE            1290
#define IDC_CHECK_COPYnDISABLESELECTEDAREA 1291
#define IDC_CHECK_HTMLHELPISSINGLE      1292
#define IDC_CHECK_bEnableLineModePaste  1292
#define IDC_CHECK_bSelectClickedURL     1293
#define IDC_EDIT_nRulerHeight           1294
#define IDC_CHECK_bEnableNoSelectCopy   1294
#define IDC_CHECK_bGrepExitConfirm      1295
#define IDC_CHECK_TILE_H                1296
#define IDC_CHECK_bDropFileAndClose     1297
#define IDC_EDIT_nDropFileNumMax        1298
#define IDC_CHECK_bCheckFileTimeStamp   1299
#define IDC_CHECK_bNotOverWriteCRLF     1300
#define IDC_COMBO_OUTLINES              1301
#define IDC_COMBO_SMARTINDENT           1302
#define IDC_BUTTON_REFERENCE            1303
#define IDC_COMBO_IMESTATE              1303
#define IDC_CHECK_bAutoCloseDlgFind     1304
#define IDC_COMBO_IMESWITCH             1304
#define IDC_CHECK_bScrollBarHorz        1305
#define IDC_CHECK_bAutoCloseDlgFuncList 1306
#define IDC_CHECK_bAutoCloseDlgReplace  1307
#define IDC_CHECK_bMarkUpBlankLineEnable 1307
#define IDC_CHECK_bFunclistSetFocusOnJump 1308
#define IDC_CHECK_CLICKKEYSEARCH        1309
#define IDC_STATIC_CURFILE              1310
#define IDC_PROGRESS                    1311
#define IDC_LIST_WORDS                  1312
#define IDC_CHECK_m_bHokanKey_RETURN    1313
#define IDC_CHECK_m_bHokanKey_TAB       1314
#define IDC_CHECK_m_bHokanKey_RIGHT     1315
#define IDC_RADIO_DFORM_0               1317
#define IDC_RADIO_DFORM_1               1318
#define IDC_EDIT_DFORM_EX               1319
#define IDC_RADIO_TFORM_0               1320
#define IDC_RADIO_TFORM_1               1321
#define IDC_EDIT_TFORM_EX               1322
#define IDC_EDIT_DFORM                  1323
#define IDC_RADIO_ALL                   1324
#define IDC_RADIO_PORTRAIT              1324
#define IDC_RADIO_BACKUP_DATETYPE1      1324
#define IDC_RADIO_REPLACE               1324
#define IDC_RADIO_DIFF_FILE1            1324
#define IDC_RADIO_OUTLINEDEFAULT        1324
#define IDC_RADIO_FROMTO                1325
#define IDC_RADIO_LANDSCAPE             1325
#define IDC_RADIO_BACKUP_DATETYPE2      1325
#define IDC_RADIO_INSERT                1325
#define IDC_RADIO_OUTLINERULEFILE       1325
#define IDC_RADIO_DIFF_FILE2            1325
#define IDC_RADIO_ADD                   1326
#define IDC_RADIO_DIFF_DST1             1326
#define IDC_EDIT2                       1327
#define IDC_EDIT_BACKUP_3               1327
#define IDC_MACROPATH                   1327
#define IDC_RADIO_DIFF_DST2             1327
#define IDC_EDIT_TAG_MAKE_CMDLINE       1327
#define IDC_EDIT_WX                     1327
#define IDC_EDIT_VERTLINE               1327
#define IDC_COMBO_m_szCommand           1328
#define IDC_EDIT_WY                     1328
#define IDC_CHECK_GETSTDOUT             1329
#define IDC_EDIT_SX                     1329
#define IDC_STATIC_CMD                  1330
#define IDC_EDIT_SY                     1330
#define IDC_STATIC_JOBNAME              1331
#define IDC_STATIC_PROGRESS             1332
#define IDC_EDIT_FROM                   1333
#define IDC_STATIC_ALL                  1334
#define IDC_CHECK_bMenuIcon             1335
#define IDC_LABEL_BACKUP_3              1336
#define IDC_LABEL_AUTOSAVE              1337
#define IDC_LABEL_BACKUP_4              1338
#define IDC_LABEL_AUTOSAVE2             1342
#define IDC_LABEL_AUTOSAVE3             1343
#define IDC_LABEL_AUTOSAVE4             1344
#define IDC_LABEL_MENUFUNC              1345
#define IDC_LABEL_MENUFUNCKIND          1346
#define IDC_LABEL_MENU                  1347
#define IDC_LABEL_MENUCHOICE            1348
#define IDC_LABEL_MENUKEYCHANGE         1349
#define IDC_LABEL_TOOLBAR               1350
#define IDC_LABEL_MENUNAME              1350
#define IDC_LABEL_KEYKIND               1351
#define IDC_LABEL_FUNCtoKEY             1352
#define IDC_LABEL_KEYtoFUNC             1353
#define IDC_TAB2                        1355
#define IDC_LABEL_LINETERMCHAR          1356
#define IDC_GROUP_FUNCKEYWND_POSITION   1357
#define IDC_LABEL_DFORM                 1358
#define IDC_LABEL_TFORM                 1359
#define IDC_LABEL_FROM                  1360
#define IDC_LABEL_TO                    1361
#define IDC_LABEL_PLSQL1                1362
#define IDC_LABEL_PLSQL2                1363
#define IDC_LABEL_PLSQL3                1364
#define IDC_LABEL_KEYWORDHELPFILE       1365
#define IDC_SPIN_BACKUP_GENS            1366
#define IDC_SPIN_AUTOBACKUP_INTERVAL    1367
#define IDC_SPIN_nRulerHeight           1368
#define IDC_CHECK_BACKUP_RETAINEXT      1369
#define IDC_SPIN_LINENUM                1372
#define IDC_LANEL_NOTE                  1373
#define IDC_CHECK_RestoreCurPosition    1375
#define IDC_STATIC_URL_CAPTION          1376
#define IDC_STATIC_URL_UR               1379
#define IDC_STATIC_URL_ORG              1380
#define IDC_CHECK_AutoMIMEDecode        1381
#define IDC_EDIT_MENUNAME               1382
#define IDC_CHECK_RestoreBookmarks      1382
#define IDC_BUTTON_TEMPCHANGE           1384
#define IDC_STATIC_EOL                  1385
#define IDC_BUTTON_JUMP                 1388
#define IDC_CHECK_LCPOS                 1389
#define IDC_SPIN_LCColNum               1390
#define IDC_LABEL_LCPOS                 1391
#define IDC_LABEL_LCPOS2                1392
#define IDC_LABEL_LCPOS3                1393
#define IDC_MACRO_REG                   1393
#define IDC_COMBO_MACROID               1394
#define IDC_BUTTON_TOP                  1394
#define IDC_BUTTON_REGEX_TOP            1394
#define IDC_BUTTON_REGEX_LAST           1395
#define IDC_MACROLIST                   1396
#define IDC_MACRONAME                   1397
#define IDC_EDIT_ABOUT                  1398
#define IDC_CHECK_SplitterWndVScroll    1399
#define IDC_BUTTON_REGEX_UPD            1399
#define IDC_CHK_WORD                    1400
#define IDC_BUTTON_REGEX_DEL            1400
#define IDC_CHECK_SameTabWidth          1400
#define IDC_MACRODIR                    1401
#define IDC_MACRODIRREF                 1402
#define IDC_BUTTON_MENUNAME             1403
#define IDC_EDIT_REGEX                  1404
#define IDC_CHECK_REGEX                 1406
#define IDC_LIST_REGEX                  1407
#define IDC_COMBO_REGEX_COLOR           1408
#define IDC_LABEL_REGEX_COLOR           1409
#define IDC_LABEL_REGEX_KEYWORD         1410
#define IDC_BUTTON_REGEX_UP             1411
#define IDC_BUTTON_REGEX_DOWN           1412
#define IDC_BUTTON_REGEX_ADD            1413
#define IDC_BUTTON_REGEX_IMPORT         1414
#define IDC_BUTTON_REGEX_EXPORT         1415
#define IDC_FRAME_REGEX                 1416
#define IDC_LABEL_REGEX_VERSION         1417
#define IDC_CHECK_INS_SPACE             1417
#define IDC_CHK_PASTE                   1418
#define IDC_CHECK_SEARCHALL             1419
#define IDC_EDIT_TYPEEXTHELP            1420
#define IDC_EDIT_TYPEEXTHTMLHELP        1421
#define IDC_BUTTON_TYPEOPENHELP         1422
#define IDC_BUTTON_TYPEOPENEXTHTMLHELP  1423
#define IDC_CHECK_TYPEHTMLHELPISSINGLE  1424
#define IDC_CHECK_DispTabWndMultiWin    1425
#define IDC_EDIT_OUTLINERULEFILE        1426
#define IDC_BUTTON_RULEFILE_REF         1427
#define IDC_EDIT_KINSOKUHEAD            1428
#define IDC_STATIC_DIFF_SRC             1428
#define IDC_EDIT_KINSOKUTAIL            1429
#define IDC_EDIT_DIFF_DST               1429
#define IDC_BUTTON_DIFF_DST             1430
#define IDC_SPIN_FUNCKEYWND_GROUPNUM    1430
#define IDC_EDIT_KINSOKUKUTO            1430
#define IDC_CHECK_DIFF_OPT_CASE         1431
#define IDC_EDIT_FUNCKEYWND_GROUPNUM    1431
#define IDC_CHECK_DIFF_OPT_SPACE        1432
#define IDC_CHECK_DIFF_OPT_SPCCHG       1433
#define IDC_STATIC_nSortType            1433
#define IDC_BTN_RELOAD                  1433
#define IDC_CHECK_DIFF_OPT_BLINE        1434
#define IDC_CHECK_DIFF_OPT_TABSPC       1435
#define IDC_BTN_NOTIFYONLY              1435
#define IDC_FRAME_DIFF_FILE12           1436
#define IDC_LIST_DIFF_FILES             1437
#define IDC_FILEUPDATEMSG               1437
#define IDC_FRAME_DIFF_DST              1438
#define IDC_LIST_CTRLCODE               1438
#define IDC_BTN_NOSUPERVISION           1438
#define IDC_BTN_CLOSE                   1439
#define IDC_UPDATEDFILENAME             1440
#define IDC_QUERYRELOADMSG              1441
#define IDC_CHECK_FNAME                 1442
#define IDC_BUTTON_FNAME_TOP            1446
#define IDC_BUTTON_FNAME_UP             1447
#define IDC_BUTTON_FNAME_DOWN           1448
#define IDC_BUTTON_FNAME_LAST           1449
#define IDC_BUTTON_FNAME_INS            1450
#define IDC_BUTTON_FNAME_ADD            1451
#define IDC_BUTTON_FNAME_UPD            1452
#define IDC_BUTTON_FNAME_DEL            1453
#define IDC_LIST_FNAME                  1454
#define IDC_EDIT_FNAME_FROM             1455
#define IDC_CHECK_TAB_ARROW             1456
#define IDC_TAB_FAVORITE                1457
#define IDC_LIST_FAVORITE_FILE          1458
#define IDC_LIST_FAVORITE_FOLDER        1459
#define IDC_LIST_FAVORITE_GREP_FILE     1460
#define IDC_LIST_FAVORITE_GREP_FOLDER   1461
#define IDC_LIST_FAVORITE_REPLACE       1462
#define IDC_LIST_FAVORITE_SEARCH        1463
#define IDC_LIST_FAVORITE_CMD           1464
#define IDC_BUTTON_CLEAR                1465
#define IDC_SLIDER_VIEW                 1466
#define IDC_BUTTON_VIEW                 1467
#define IDC_LIST_TAGJUMP                1468
#define IDC_WINCAPTION_ACTIVE           1469
#define IDC_WINCAPTION_INACTIVE         1470
#define IDC_CHECK_HOKANBYFILE           1470
#define IDC_BUTTON_TAG_MAKE_REF         1471
#define IDC_TABWND_CAPTION              1471
#define IDC_CHECK_TAG_MAKE_RECURSE      1472
#define IDC_EDIT_TAG_MAKE_FOLDER        1473
#define IDC_FRAME_SEARCH_MSG            1474
#define IDC_CHECK_DIFF_EXEC_STATE       1475
#define IDC_STATIC_FAVORITE_MSG         1476
#define IDC_CHECK_REALTIMEVIEW          1477
#define IDC_CHECK_BOM                   1478
#define IDC_CHECK_GREPREALTIME          1479
#define IDC_RADIO_WINSIZE_DEF           1480
#define IDC_RADIO_WINSIZE_SAVE          1481
#define IDC_RADIO_WINSIZE_SET           1482
#define IDC_SPIN_WX                     1483
#define IDC_SPIN_WY                     1484
#define IDC_RADIO_WINPOS_DEF            1485
#define IDC_RADIO_WINPOS_SAVE           1486
#define IDC_RADIO_WINPOS_SET            1487
#define IDC_SPIN_SX                     1488
#define IDC_SPIN_SY                     1489
#define IDC_COMBO_WINTYPE               1490
#define IDC_BUTTON_WINSIZE              1491
#define IDC_CHECK_QueryIfCodeChange     1492
#define IDC_HOTKEY1                     1493
#define IDC_CHECK_AlertIfFileNotExist   1493
#define IDC_COMBO1                      1494
#define IDC_BUTTON_KEYWORD_SELECT       1495
#define IDC_COMBO2                      1495
#define IDC_COMBO3                      1496
#define IDC_STATIC_KEYWORD_COUNT        1496
#define IDC_COMBO4                      1497
#define IDC_BUTTON_KEYSETRENAME         1497
#define IDC_COMBO5                      1498
#define IDC_BUTTON_KEYCLEAN             1498
#define IDC_COMBO6                      1499
#define IDC_KEYWORD                     1499
#define IDC_COMBO7                      1500
#define IDC_STATIC_KEYWORD              1500
#define IDC_COMBO8                      1501
#define IDC_CHECK_ICASE                 1501
#define IDC_COMBO9                      1502
#define IDC_CHECK_ANYWHERE              1502
#define IDC_COMBO10                     1503
#define IDC_EDIT_BACKUPFILE             1504
#define IDC_LABEL_BACKUP_HELP           1505
#define IDC_CHECK_BACKUP_ADVANCED       1506
#define IDC_RADIO_BACKUP_DATETYPE1A     1507
#define IDC_RADIO_BACKUP_DATETYPE2A     1508
#define IDC_LABEL_BACKUP_HELP2          1509
#define IDC_CHECK_MEMDC                 1510
#define IDC_STATIC_COLOR                1510
#define IDC_BUTTON_SELALL               1511
#define IDC_BUTTON_SELNOTING            1512
#define IDC_LIST_ITEMINFO               1514
#define IDC_CHECK_NoFilterSaveNew       1515
#define IDC_CHECK_NoFilterSaveFile      1516
#define IDC_CHECK_CLOSEALLCONFIRM       1517
#define IDC_CHECK_ANTIALIAS             1518
#define IDC_CHECK_RetainEmptyWindow     1518
#define IDC_BUTTON_DIRECTPAGE           1519
#define IDC_CHECK_CloseOneWin           1519
#define IDC_CHECK_MacroOnOpened         1520
#define IDC_CHECK_MacroOnTypeChanged    1521
#define IDC_CHECK_MacroOnSave           1522
#define IDC_CHECK_bCaretTextForSearch   1520
#define IDC_CHECK_ChgWndByWheel         1521
#define IDC_LABEL_REGEXP                1522
#define IDC_EDIT_REGEXPLIB              1524
#define IDC_LABEL_REGEXP_VER            1525
#define IDC_COMBO_WHEEL_PAGESCROLL      1526
#define IDC_COMBO_WHEEL_HSCROLL         1527
#define IDC_CHECK_ACCELTBL_EACHWIN      1528
#define IDC_RADIO_OUTPUT                1536
#define IDC_RADIO_EDITWINDOW            1537
#define IDC_CHECK_SENDSTDIN             1538
#define IDD_PROP_TOOLBAR                1539
#define IDC_CHECK_SortTabList           1540
#define IDC_COMBO_WRAPMETHOD            1541
#define IDC_SPIN_ALERT_FILESIZE         1552
#define IDC_EDIT_ALERT_FILESIZE         1553
#define IDC_CHECK_ALERT_IF_LARGEFILE    1554
#define IDM_POPLAST                     4047
#define IDS_AUTHOR_PAGE                 4054
#define IDS_ABOUT_DESCRIPTION           4056
#define IDM_POPLAST2                    4064
#define ID_IS4072                       4072
#define IDD_PROPTYPESP1                 5101
#define IDD_PROP_CUSTMENU               5103
#define IDD_PROP_FORMAT                 5104
#define IDD_PROP_HELPER                 5105
#define IDD_PROP_COLOR                  5106
#define IDD_PROP_KEYBIND                5107
#define IDD_PROP_WIN                    5108
#define IDD_PROP_EDIT                   5109
#define IDD_PROP_TAB                    5110
#define IDD_PROP_GREP                   5111
#define IDD_PROP_BACKUP                 5112
#define IDD_OPERATIONRUNNING            5113
#define IDD_PROP_KEYBIND1               5114
#define IDD_PROPTYPESP2                 5114
#define IDD_DIFF                        5115
#define IDD_CTRLCODE                    5116
#define IDD_WINPOSSIZE                  5117
#define IDD_PROP_KEYHELP                5119
#define IDC_FRAME_KEYHELP               5120
#define IDC_LIST_KEYHELP                5121
#define IDC_LABEL_KEYHELP_KEYWORD       5122
#define IDC_EDIT_KEYHELP                5123
#define IDC_LABEL_KEYHELP_TITLE         5124
#define IDC_COMBO_KEYHELP_COLOR         5125
#define IDC_BUTTON_KEYHELP_INS          5126
#define IDC_BUTTON_KEYHELP_ADD          5127
#define IDC_BUTTON_KEYHELP_UPD          5128
#define IDC_BUTTON_KEYHELP_DEL          5129
#define IDC_BUTTON_KEYHELP_TOP          5130
#define IDC_BUTTON_KEYHELP_UP           5131
#define IDC_BUTTON_KEYHELP_DOWN         5132
#define IDC_BUTTON_KEYHELP_LAST         5133
#define IDC_BUTTON_KEYHELP_IMPORT       5134
#define IDC_BUTTON_KEYHELP_EXPORT       5135
#define IDC_LABEL_KEYHELP_ABOUT         5136
#define IDC_CHECK_KEYHELP               5137
#define IDC_CHECK_TYPE_KEYHELPUSE       5138
#define IDC_LABEL_KEYHELP_PRIOR         5139
#define IDC_BUTTON_KEYHELP_REF          5140
#define IDC_CHECK_KEYHELP_ALLSEARCH     5141
#define IDC_CHECK_KEYHELP_KEYDISP       5142
#define IDC_CHECK_KEYHELP_PREFIX        5143
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        249
#define _APS_NEXT_COMMAND_VALUE         4073
#define _APS_NEXT_CONTROL_VALUE         1529
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
