//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by sakura_rc.rc
//
#define IDOK2                           3
#define IDR_MENU1                       102
#define IDD_PROP1P1                     107
#define IDD_FIND                        109
#define IDD_PROP1P2                     110
#define IDD_PROP_FILE                   110
#define IDR_TRAYMENU_L                  113
#define IDD_ABOUT                       115
#define IDD_JUMP                        118
#define IDD_FUNCLIST                    122
#define IDD_PROP1P3                     124
#define IDD_SENDMAIL                    129
#define IDD_PROP1P4                     130
#define IDD_PROP_MAIL                   130
#define IDD_PROP1P5                     131
#define IDD_GREP                        132
#define IDD_GREPRUNNING                 134
#define IDD_SENDINGMAIL                 136
#define IDD_REPLACE                     137
#define IDD_WORDS                       140
#define IDD_TYPELIST                    147
#define IDD_TYPELIST_PROP               148
#define IDD_PROPERTY_FILE               152
#define IDD_PROP_KEYWORD                153
#define IDD_INPUT1                      154
#define IDD_REPLACERUNNING              160
#define IDD_SETUP                       162
#define IDD_COMPARE                     168
#define IDD_PRINTPREVIEWBAR             170
#define IDD_PRINTSETTING                174
#define IDD_EXITING                     175
#define IDD_DEBUG                       177
#define IDD_KEYMACRO                    178
#define IDD_OUTLINES                    181
#define IDD_DIALOG6                     182
#define IDD_EXEC                        182
#define IDD_HOKAN                       186
#define IDD_EXECCMD_TEST                188
#define IDD_EXECRUNNING                 191
#define IDD_PRINTING                    192
#define IDD_PRINTPAGE                   193
#define IDD_DIALOG1                     195
#define IDB_MYTOOL                      200
#define IDB_OPENED                      201
#define IDB_OPENED_THIS                 202
#define IDB_PRINTER                     203
#define IDD_EXTCMD                      215
#define IDD_PROP_MACRO                  217
#define IDC_CURSOR_COPYARROW            220
#define IDC_CURSOR_HAND                 221
#define IDC_CURSOR_MOVEARROW            222
#define IDI_ICON_STD                    230
#define IDI_ICON_DEBUG                  231
#define IDI_ICON_HANA                   232
#define IDI_ICON_MOJI                   233
#define IDI_ICON_GREP                   240
#define IDC_HIDE                        1000
#define IDC_CHK_LOHICASE                1006
#define IDC_CHECK_DISPLINE              1007
#define IDC_CHECK_INDENT                1009
#define IDC_CHK_REGULAREXP              1010
#define IDC_CHECK_INDENT_WSPACE         1011
#define IDC_CHECK4                      1013
#define IDC_CHECK_GTJW_RETURN           1013
#define IDC_CHECK_FREECARET             1014
#define IDC_BUTTON1                     1015
#define IDC_BUTTON_CLEAR_MRU_FOLDER     1016
#define IDC_BUTTON_RELEASE              1016
#define IDC_COMBO_TEXT                  1021
#define IDC_COMBO_TEXT2                 1022
#define IDC_CHECK5                      1023
#define IDC_CHECK_GTJW_LDBLCLK          1023
#define IDC_EDIT_MAXLINELEN             1029
#define IDC_EDIT_CHARSPACE              1031
#define IDC_SPIN_MAXLINELEN             1034
#define IDC_SPIN_CHARSPACE              1035
#define IDC_EDIT_LINESPACE              1037
#define IDC_SPIN_LINESPACE              1038
#define IDC_SPIN_REPEATEDSCROLLLINENUM  1039
#define IDC_EDIT_TABVIEWSTRING          1039
#define IDC_COMBO_TABSPACE              1050
#define IDC_BUTTON_TEXTCOLOR            1056
#define IDC_BUTTON_BACKCOLOR            1060
#define IDC_BUTTON_CRLFCOLOR            1061
#define IDC_BUTTON_CRLFBACKCOLOR        1062
#define IDC_BUTTON_GYOUCOLOR            1063
#define IDC_BUTTON_TABCOLOR             1064
#define IDC_STATIC_JRE32VER             1065
#define IDC_BUTTON_ZENCOLOR             1065
#define IDC_BUTTON_EOFCOLOR             1066
#define IDC_BUTTON_GYOUBACKCOLOR        1067
#define IDC_BUTTON_TABBACKCOLOR         1068
#define IDC_CHECK_EXCVLUSIVE_NO         1069
#define IDC_BUTTON_ZENBACKCOLOR         1069
#define IDC_CHECK_EXCVLUSIVE_READWRITE  1070
#define IDC_BUTTON_EOFBACKCOLOR         1070
#define IDC_CHECK_EXCVLUSIVE_WRITE      1071
#define IDC_BUTTON_CCPPKEYWORDCOLOR     1071
#define IDC_BUTTON_CCPPKEYWORDBACKCOLOR 1072
#define IDC_BUTTON_COMMENTCOLOR         1073
#define IDC_EDIT_LINENUM                1074
#define IDC_BUTTON_COMMENTBACKCOLOR     1074
#define IDC_BUTTON_SSTRINGCOLOR         1075
#define IDC_CHECK1                      1076
#define IDC_CHECK_BACKUP                1076
#define IDC_CHECK_DISPTAB               1076
#define IDC_CHECK_EXITCONFIRM           1076
#define IDC_CHECK_PLSQL                 1076
#define IDC_CHECK_SHIFT                 1076
#define IDC_CHK_FROMTHISTEXT            1076
#define IDC_CHECK_TOOLBARISFLAT         1076
#define IDC_BUTTON_SSTRINGBACKCOLOR     1077
#define IDC_CHECK_LCPOS2                1077
#define IDC_RADIO_BACKUP_TYPE1          1078
#define IDC_RADIO_OUTPUTMARKED          1078
#define IDC_RADIO_ALLAREA               1078
#define IDC_RADIO_CARETTYPE1            1078
#define IDC_BUTTON_WSTRINGCOLOR         1078
#define IDC_RADIO_nRulerType_1          1078
#define IDC_CHECK_LCPOS3                1078
#define IDC_RADIO_BACKUP_TYPE2          1079
#define IDC_BUTTON_WSTRINGBACKCOLOR     1079
#define IDC_RADIO_FUNCKEYWND_PLACE2     1079
#define IDC_CHECK3                      1080
#define IDC_CHECK_BACKUP_YEAR           1080
#define IDC_CHECK_DISPEOF               1080
#define IDC_CHECK_ALT                   1080
#define IDC_CHECK_BACKUP_HOUR           1081
#define IDC_CHECK_KEYWORDCCPP           1081
#define IDC_CHECK_BACKUP_MIN            1082
#define IDC_CHECK_COMMENT               1082
#define IDC_CHECK_BACKUP_SEC            1083
#define IDC_CHECK_SSTRING               1083
#define IDC_CHECK_BACKUPDIALOG          1084
#define IDC_CHECK_WSTRING               1084
#define IDC_CHECK_BACKUPFOLDER          1085
#define IDC_CHECK_UNDERLINE             1085
#define IDC_EDIT1                       1086
#define IDC_EDIT_BACKUPFOLDER           1086
#define IDC_EDIT_EXTHELP1               1086
#define IDC_EDIT_PLSQL_E1               1086
#define IDC_EDIT_EMAILUSERNAME          1086
#define IDC_EDIT_BLOCKCOMMENT_FROM      1086
#define IDC_EDIT_NAME                   1086
#define IDC_EDIT_TYPENAME               1086
#define IDC_BUTTON_BACKUP_FOLDER_REF    1087
#define IDC_BUTTON_REPALCE              1087
#define IDC_BUTTON_DELETE               1087
#define IDC_BUTTON_UNDERLINECOLOR       1087
#define IDC_BUTTON_DELKEYWORD           1087
#define IDC_EDIT_EXTHTMLHELP            1087
#define IDC_EDIT_TFORM                  1087
#define IDC_EDIT_BLOCKCOMMENT_FROM2     1087
#define IDC_CHECK_BACKUP_MONTH          1088
#define IDC_BUTTON3                     1088
#define IDC_BUTTON_INSERTSEPARATOR      1088
#define IDC_EDIT_KEYWORDHELPFILE        1088
#define IDC_BUTTON_ZOOMUP               1088
#define IDC_CHECK_BACKUP_DAY            1089
#define IDC_BUTTON_KEYWORDHELPFILE_REF  1089
#define IDC_BUTTON_INSERTSEPARATOR2     1089
#define IDC_CHECK_DISPZENSPACE          1090
#define IDC_RADIO_BACKUP_TYPE3          1090
#define IDC_CHECK2                      1091
#define IDC_CHECK_AUTOSAVE              1091
#define IDC_LIST1                       1092
#define IDC_CHECK_DispTOOLBAR           1092
#define IDC_EDIT_BACKUPFOLDER2          1092
#define IDC_EDIT_AUTOBACKUP_INTERVAL    1092
#define IDC_CHECK_DISPCRLF              1095
#define IDC_BUTTON_OPENHELP1            1096
#define IDC_BUTTON_OPENEXTHTMLHELP      1097
#define IDC_EDIT_REPEATEDSCROLLLINENUM  1098
#define IDC_BUTTON_HELP                 1099
#define IDC_EDIT4                       1105
#define IDC_EDIT_TO                     1105
#define IDC_EDIT_CC                     1106
#define IDC_EDIT_SUBJECT                1107
#define IDC_EDIT_BCC                    1108
#define IDC_EDIT_EMAILUSERADDRESS       1109
#define IDC_EDIT_BLOCKCOMMENT_TO        1109
#define IDC_EDIT_EXT                    1109
#define IDC_EDIT_TYPEEXTS               1109
#define IDC_EDIT_MARGINTY               1109
#define IDC_EDIT_nRulerBottomSpace      1109
#define IDC_EDIT_SMTPSERVER             1110
#define IDC_EDIT_LINECOMMENT            1110
#define IDC_EDIT_INDENTCHARS            1110
#define IDC_EDIT_MAX_MRU_FOLDER         1110
#define IDC_EDIT_MARGINBY               1110
#define IDC_EDIT_SMTPPORT               1111
#define IDC_EDIT_LINECOMMENT2           1111
#define IDC_EDIT_MARGINLX               1111
#define IDC_LIST_FUNC                   1112
#define IDC_EDIT_SMTPSERVER2            1112
#define IDC_EDIT_MARGINRX               1112
#define IDC_EDIT_BLOCKCOMMENT_TO2       1112
#define IDC_COMBO_FUNCKIND              1113
#define IDC_EDIT_SMTPPORT2              1113
#define IDC_EDIT_DANSPACE               1113
#define IDC_EDIT_LINECOMMENT3           1113
#define IDC_LIST_KEY                    1114
#define IDC_CHECK_CTRL                  1115
#define IDC_CHECK_ADDCRLFWHENCOPY       1116
#define IDC_COMBO1                      1118
#define IDC_COMBO_FILE                  1118
#define IDC_COMBO_FOLDER                1119
#define IDC_COMBO_SETTINGNAME           1119
#define IDC_COMBO_PAPER                 1120
#define IDC_BUTTON_FOLDER               1121
#define IDC_CHK_SUBFOLDER               1122
#define IDC_STATIC_CURPATH              1123
#define IDC_STATIC_HITCOUNT             1124
#define IDC_BUTTON_CAUTION              1126
#define IDC_STATIC_VER                  1127
#define IDC_LIST_ASSIGNEDKEYS           1129
#define IDC_STATIC_MSG                  1130
#define IDC_PROGRESS_SENDING            1131
#define IDC_RADIO_OUTPUTLINE            1132
#define IDC_RADIO_SELECTEDAREA          1133
#define IDC_BUTTON_REPALCEALL           1134
#define IDC_BUTTON_SEARCHPREV           1135
#define IDC_BUTTON_SEARCHNEXT           1137
#define IDC_LIST_RES                    1138
#define IDC_TREE1                       1140
#define IDC_BUTTON_ADD                  1141
#define IDC_BUTTON_INSERT               1142
#define IDC_BUTTON_UP                   1143
#define IDC_BUTTON_DOWN                 1144
#define IDC_BUTTON_SAMEBKCOLOR          1144
#define IDC_CHECK_REPEATEDSCROLLSMOOTH  1145
#define IDC_BUTTON_SAMETEXTCOLOR        1145
#define IDC_COMBO_CODE                  1146
#define IDC_RADIO_CARETTYPE0            1147
#define IDC_COMBO_EOL                   1147
#define IDC_BUTTON_COPY                 1149
#define IDC_RADIO_ESCAPETYPE_1          1150
#define IDC_RADIO_ESCAPETYPE_2          1151
#define IDC_LIST_TYPES                  1153
#define IDC_RADIO_OUTPUTSTYLE1          1158
#define IDC_RADIO_nRulerType_0          1158
#define IDC_EDIT_VER                    1163
#define IDC_COMBO_PLSQLBLOCKS           1164
#define IDC_COMBO_MRU                   1167
#define IDC_CHECK_KEYWORDCASE           1168
#define IDC_COMBO_OPENFOLDER            1169
#define IDC_BUTTON_ADDKEYWORD           1170
#define IDC_BUTTON_IMPORT               1171
#define IDC_BUTTON_EXPORT               1173
#define IDC_BUTTON_ADDSET               1176
#define IDC_BUTTON_EDITKEYWORD          1177
#define IDC_BUTTON_DELSET               1178
#define IDC_COMBO_SET                   1179
#define IDC_COMBO_SET2                  1180
#define IDC_LIST_KEYWORD                1181
#define IDC_SPIN_MAX_MRU_FILE           1184
#define IDC_SPIN_MAX_MRU_FOLDER         1185
#define IDC_SPIN_nDropFileNumMax        1185
#define IDC_SPIN_nRulerBottomSpace      1185
#define IDC_EDIT_MAX_MRU_FILE           1186
#define IDC_SPIN_PLSQL                  1186
#define IDC_SPIN_PLSQL_E1               1186
#define IDC_SPIN_LCColNum2              1186
#define IDC_BUTTON_CLEAR_MRU_FILE       1187
#define IDC_SPIN_LCColNum3              1187
#define IDC_COMBO_MENU                  1188
#define IDC_RADIO_FUNCKEYWND_PLACE1     1190
#define IDC_CHECK_DispFUNCKEYWND        1191
#define IDC_CHECK_NOTIFYNOTFOUND        1192
#define IDC_EDIT_MIDASHIKIGOU           1193
#define IDC_EDIT_INYOUKIGOU             1194
#define IDC_PROGRESS_REPLACE            1195
#define IDC_STATIC_KENSUU               1197
#define IDC_STATIC_MYICON               1198
#define IDC_CHECK_USEHOKAN              1200
#define IDC_EDIT_HOKANFILE              1201
#define IDC_CHECK_USEKEYWORDHELP        1202
#define IDC_BUTTON_HOKANFILE_REF        1203
#define IDC_STATIC_UPDATE               1204
#define IDC_BUTTON_CONTACT              1207
#define IDC_BUTTON_DOWNLOAD             1208
#define IDC_LIST_OLDVERSION             1209
#define IDC_STATIC_MESSAGE              1210
#define IDC_LIST_COLORS                 1211
#define IDC_CHECK_DISP                  1212
#define IDC_CHECK_FAT                   1213
#define IDC_RADIO_LINENUM_LAYOUT        1214
#define IDC_RADIO_LINENUM_CRLF          1215
#define IDC_STATIC_HAIKEI               1216
#define IDC_CHK_KANJICODEAUTODETECT     1217
#define IDC_RADIO_LINETERMTYPE2         1218
#define IDC_EDIT_LINETERMCHAR           1220
#define IDC_RADIO_LINETERMTYPE0         1221
#define IDC_RADIO_LINETERMTYPE1         1222
#define IDC_LIST_FILES                  1223
#define IDC_STATIC_COMPARESRC           1224
#define IDC_CHECK_HOKANLOHICASE         1225
#define IDC_BUTTON_NEXTPAGE             1227
#define IDC_BUTTON_ZOOMDOWN             1228
#define IDC_BUTTON_PRINTSETTING         1232
#define IDC_EDIT_LINECOMMENTPOS         1234
#define IDC_BUTTON_PREVPAGE             1235
#define IDC_EDIT_LINECOMMENTPOS2        1235
#define IDC_SPIN_MARGINTY               1236
#define IDC_EDIT_LINECOMMENTPOS3        1236
#define IDC_SPIN_MARGINBY               1237
#define IDC_SPIN_MARGINLX               1238
#define IDC_SPIN_MARGINRX               1239
#define IDC_SPIN_FONTWIDTH              1241
#define IDC_SPIN_DANSUU                 1242
#define IDC_EDIT_FOOT1                  1243
#define IDC_COMBO_FONT_HAN              1244
#define IDC_COMBO_FONT_ZEN              1245
#define IDC_SPIN_DANSPACE               1247
#define IDC_COMBO_PAPERORIENT           1258
#define IDC_EDIT_FONTWIDTH              1259
#define IDC_EDIT_DANSUU                 1260
#define IDC_CHECK_WORDWRAP              1261
#define IDC_CHECK_LINENUMBER            1262
#define IDC_BUTTON_EDITSETTINGNAME      1263
#define IDC_STATIC_PAGENUM              1264
#define IDC_STATIC_ZOOM                 1265
#define IDC_EDIT_HEAD1                  1270
#define IDC_STATIC_PRNDEV               1271
#define IDC_STATIC_PAPER                1272
#define IDC_CHECK_WINSIZE               1272
#define IDC_EDIT_KEYSFUNC               1273
#define IDC_BUTTON_ASSIGN               1274
#define IDC_BUTTON2                     1275
#define IDC_BUTTON4                     1276
#define IDC_BUTTON_CURRENTFOLDER        1277
#define IDC_EDIT_DEBUG                  1278
#define IDC_CHECK_USETRAYICON           1279
#define IDC_CHECK_STAYTASKTRAY          1280
#define IDC_CHECK_DispSTATUSBAR         1281
#define IDC_RADIO_OUTPUTSTYLE2          1282
#define IDC_STATIC_ENABLECOLMNS         1283
#define IDC_STATIC_ENABLELINES          1284
#define IDC_HOTKEY_TRAYMENU             1286
#define IDC_CHECK_ENABLEUNMODIFIEDOVERWRITE 1287
#define IDC_CHECK_DRAGDROP              1289
#define IDC_CHECK_DROPSOURCE            1290
#define IDC_CHECK_COPYnDISABLESELECTEDAREA 1291
#define IDC_CHECK_HTMLHELPISSINGLE      1292
#define IDC_CHECK_bSelectClickedURL     1293
#define IDC_EDIT_nRulerHeight           1294
#define IDC_CHECK_bGrepExitConfirm      1295
#define IDC_CHECK_TILE_H                1296
#define IDC_CHECK_bDropFileAndClose     1297
#define IDC_CHECK_TILE_H2               1297
#define IDC_EDIT_nDropFileNumMax        1298
#define IDC_CHECK_bCheckFileTimeStamp   1299
#define IDC_CHECK_bNotOverWriteCRLF     1300
#define IDC_COMBO_OUTLINES              1301
#define IDC_BUTTON_HELPER               1302
#define IDC_COMBO_SMARTINDENT           1302
#define IDC_BUTTON_REFERENCE            1303
#define IDC_COMBO_IMESTATE              1303
#define IDC_CHECK_bAutoCloseDlgFind     1304
#define IDC_COMBO_IMESWITCH             1304
#define IDC_CHECK_bScrollBarHorz        1305
#define IDC_CHECK_bAutoCloseDlgFuncList 1306
#define IDC_CHECK_bAutoCloseDlgReplace  1307
#define IDC_STATIC_CURFILE              1310
#define IDC_PROGRESS                    1311
#define IDC_LIST_WORDS                  1312
#define IDC_CHECK_m_bHokanKey_RETURN    1313
#define IDC_CHECK_m_bHokanKey_TAB       1314
#define IDC_CHECK_m_bHokanKey_RIGHT     1315
#define IDC_CHECK_m_bHokanKey_SPACE     1316
#define IDC_RADIO_DFORM_0               1317
#define IDC_RADIO_DFORM_1               1318
#define IDC_EDIT_DFORM_EX               1319
#define IDC_RADIO_TFORM_0               1320
#define IDC_RADIO_TFORM_1               1321
#define IDC_EDIT_TFORM_EX               1322
#define IDC_EDIT_DFORM                  1323
#define IDC_RADIO1                      1324
#define IDC_RADIO_ALL                   1324
#define IDC_RADIO_PORTLAIT              1324
#define IDC_RADIO2                      1325
#define IDC_RADIO_FROMTO                1325
#define IDC_RADIO_LANDSCAPE             1325
#define IDC_RADIO3                      1326
#define IDC_EDIT2                       1327
#define IDC_EDIT_BACKUP_3               1327
#define IDC_MACROPATH                   1327
#define IDC_COMBO_m_szCommand           1328
#define IDC_CHECK_GETSTDOUT             1329
#define IDC_STATIC_CMD                  1330
#define IDC_STATIC_JOBNAME              1331
#define IDC_STATIC_PROGRESS             1332
#define IDC_EDIT_FROM                   1333
#define IDC_STATIC_ALL                  1334
#define IDC_CHECK_bMenuIcon             1335
#define IDC_LABEL_BACKUP_3              1336
#define IDC_LABEL_AUTOSAVE              1337
#define IDC_LABEL_BACKUP_4              1338
#define IDC_LABEL_AUTOSAVE2             1342
#define IDC_LABEL_AUTOSAVE3             1343
#define IDC_LABEL_AUTOSAVE4             1344
#define IDC_LABEL_MENUFUNC              1345
#define IDC_LABEL_MENUFUNCKIND          1346
#define IDC_LABEL_MENU                  1347
#define IDC_LABEL_MENUCHOICE            1348
#define IDC_LABEL_MENUKEYCHANGE         1349
#define IDC_LABEL_TOOLBAR               1350
#define IDC_LABEL_KEYKIND               1351
#define IDC_LABEL_FUNCtoKEY             1352
#define IDC_LABEL_KEYtoFUNC             1353
#define IDC_TAB2                        1355
#define IDC_LABEL_LINETERMCHAR          1356
#define IDC_GROUP_FUNCKEYWND_POSITION   1357
#define IDC_LABEL_DFORM                 1358
#define IDC_LABEL_TFORM                 1359
#define IDC_LABEL_FROM                  1360
#define IDC_LABEL_TO                    1361
#define IDC_LABEL_PLSQL1                1362
#define IDC_LABEL_PLSQL2                1363
#define IDC_LABEL_PLSQL3                1364
#define IDC_LABEL_KEYWORDHELPFILE       1365
#define IDC_SPIN_BACKUP_GENS            1366
#define IDC_SPIN_AUTOBACKUP_INTERVAL    1367
#define IDC_SPIN_nRulerHeight           1368
#define IDC_SPIN_LINENUM                1372
#define IDC_LANEL_NOTE                  1373
#define IDC_CHECK_RestoreCurPosition    1375
#define IDC_STATIC_URL_CAPTION          1376
#define IDC_STATIC_URL_UR               1379
#define IDC_STATIC_URL_ORG              1380
#define IDC_CHECK_AutoMIMEDecode        1381
#define IDC_EDIT_MENUNAME               1382
#define IDC_BUTTON_TEMPCHANGE           1384
#define IDC_STATIC_EOL                  1385
#define IDC_BUTTON_JUMP                 1388
#define IDC_CHECK_LCPOS                 1389
#define IDC_SPIN_LCColNum               1390
#define IDC_LABEL_LCPOS                 1391
#define IDC_LABEL_LCPOS2                1392
#define IDC_LABEL_LCPOS3                1393
#define IDC_MACRO_REF                   1392
#define IDC_MACRO_REG                   1393
#define IDC_COMBO_MACROID               1394
#define IDC_MACRO_DEL                   1395
#define IDC_MACROLIST                   1396
#define IDC_MACRONAME                   1397
#define FILEOPENORD1                    1538
#define IDD_PROP1P6                     1539
#define IDD_PROP_TOOLBAR                1539
#define IDM_POPLAST                     4047
#define IDS_AUTHOR_PAGE                 4054
#define IDS_AUTHOR_MAIL                 4055
#define IDM_POPLAST2                    4064
#define ID_MENUITEM4071                 4071
#define IDD_PROPTYPESP1                 5101
#define IDD_ABOUT1                      5102
#define IDD_PROP1P8                     5103
#define IDD_PROP_CUSTMENU               5103
#define IDD_PROP1P9                     5104
#define IDD_PROP_FORMAT                 5104
#define IDD_PROP_HELPER                 5105
#define IDD_PROP1P3_NEW                 5106
#define IDD_PROP_COLOR                  5106
#define IDD_PROP1P5_NEW                 5107
#define IDD_PROP_KEYBIND                5107
#define IDD_PROP_WIN                    5108
#define IDD_PROP_EDIT                   5109
#define IDD_PROP_URL                    5110
#define IDD_PROP_GREP                   5111
#define IDD_PROP_BACKUP                 5112
#define IDD_OPERATIONRUNNING            5113
#define IDD_PROP_KEYBIND1               5114
#define IDS_STRING31581                 31581
#define IDC_EXECINFO                    -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        218
#define _APS_NEXT_COMMAND_VALUE         4072
#define _APS_NEXT_CONTROL_VALUE         1398
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
