//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by sakura_rc.rc
//
#define ID_RC_TYPE_INI                  100
#define IDR_MENU1                       102
#define IDR_TRAYMENU_L                  103
#define IDD_FIND                        110
#define IDD_ABOUT                       111
#define IDD_JUMP                        112
#define IDD_FUNCLIST                    113
#define IDD_GREP                        114
#define IDD_GREPRUNNING                 115
#define IDD_REPLACE                     116
#define IDD_REPLACERUNNING              117
#define IDD_PROPERTY_FILE               118
#define IDD_INPUT1                      119
#define IDD_COMPARE                     120
#define IDD_PRINTPREVIEWBAR             121
#define IDD_PRINTSETTING                122
#define IDD_EXITING                     123
//#define IDD_DEBUG                       124
#define IDD_EXEC                        125
#define IDD_EXECRUNNING                 126
#define IDD_HOKAN                       127
#define IDD_PRINTING                    128
//#define IDD_PRINTPAGE                   129
#define IDD_FILEOPEN                    130
#define IDD_FILEUPDATEQUERY             131
#define IDD_FAVORITE                    132
#define IDD_TAGJUMPLIST                 133
#define IDD_TAG_MAKE                    134
#define IDD_OPERATIONRUNNING            135
#define IDD_DIFF                        136
#define IDD_CTRLCODE                    137
#define IDD_MACRORUNNING                138
#define IDD_SETCHARSET                  139
#define IDD_GREP_REPLACE                140
#define IDD_WINLIST                     141
#define IDB_MYTOOL                      200
#define IDB_SCROLL_CENTER               201
#define IDB_SCROLL_VERTICAL             202
#define IDB_SCROLL_HORIZONTAL           203
#define IDI_ICON_STD                    210
//#define IDI_ICON_DEBUG                  211
#define IDI_ICON_GREP                   212
#define IDI_PRINTER                     215
#define IDC_CURSOR_COPYARROW            220
//#define IDC_CURSOR_HAND                 221
#define IDC_CURSOR_MOVEARROW            222
#define IDC_CURSOR_RVARROW              223
#define IDC_CURSOR_ISEARCH_F            224
#define IDC_CURSOR_ISEARCH_B            225
//#define IDC_CURSOR_TAB_LEFT             226
//#define IDC_CURSOR_TAB_RIGHT            227
#define IDC_CURSOR_TAB_SEPARATE         228
#define IDC_CURSOR_TAB_JOIN             229
#define IDC_CURSOR_AUTOSCROLL_CENTER   230
#define IDC_CURSOR_AUTOSCROLL_VERTICAL 231
#define IDC_CURSOR_AUTOSCROLL_HORIZONTAL 232
#define IDC_CURSOR_AUTOSCROLL_UP       233
#define IDC_CURSOR_AUTOSCROLL_DOWN     234
#define IDC_CURSOR_AUTOSCROLL_LEFT     235
#define IDC_CURSOR_AUTOSCROLL_RIGHT    236
#define IDC_CURSOR_AUTOSCROLL_UP_LEFT  237
#define IDC_CURSOR_AUTOSCROLL_UP_RIGHT 238
#define IDC_CURSOR_AUTOSCROLL_DOWN_LEFT 239
#define IDC_CURSOR_AUTOSCROLL_DOWN_RIGHT 240
#define IDC_BUTTON_PRINTERSELECT        1000
#define IDC_CHK_LOHICASE                1001
#define IDC_CHECK_INDENT                1002
#define IDC_CHK_REGULAREXP              1003
#define IDC_COMBO_INDENTLAYOUT          1004
#define IDC_CHECK_INDENT_WSPACE         1005
#define IDC_CHECK_STOPS_BOTH_ENDS_WHEN_SEARCH_WORD 1006
#define IDC_CHECK_GTJW_RETURN           1007
#define IDC_CHECK_STOPS_BOTH_ENDS_WHEN_SEARCH_PARAGRAPH 1008
#define IDC_CHECK_RTRIM_PREVLINE        1009
#define IDC_CHECK_FREECARET             1010
#define IDC_BUTTON_CLEAR_MRU_FOLDER     1011
#define IDC_BUTTON_RELEASE              1012
#define IDC_COMBO_TEXT                  1013
#define IDC_COMBO_TEXT2                 1014
#define IDC_CHECK_GTJW_LDBLCLK          1015
#define IDC_EDIT_MAXLINELEN             1016
#define IDC_EDIT_CHARSPACE              1017
#define IDC_SPIN_MAXLINELEN             1018
#define IDC_SPIN_CHARSPACE              1019
#define IDC_EDIT_LINESPACE              1020
#define IDC_SPIN_LINESPACE              1021
#define IDC_SPIN_REPEATEDSCROLLLINENUM  1022
#define IDC_EDIT_TABVIEWSTRING          1023
#define IDC_SPIN_TABSPACE               1024
#define IDC_EDIT_TABSPACE               1025
#define IDC_BUTTON_TEXTCOLOR            1026
#define IDC_BUTTON_BACKCOLOR            1027
#define IDC_STATIC_JRE32VER             1028
#define IDC_COMBO_FILESHAREMODE         1029
#define IDC_CHECK_bUneditableIfUnwritable 1030
#define IDC_CHECK_NOMOVE_ACTIVATE_BY_MOUSE 1032
#define IDC_EDIT_LINENUM                1033
#define IDC_CHECK_BACKUP                1034
#define IDC_CHECK_EXITCONFIRM           1035
#define IDC_CHECK_PLSQL                 1036
#define IDC_CHECK_SHIFT                 1037
#define IDC_CHK_FROMTHISTEXT            1038
#define IDC_CHECK_TOOLBARISFLAT         1039
#define IDC_CHECK_RELOADWHENEXECUTE     1040
#define IDC_CHECK_DOCICON               1041
#define IDC_CHECK_LCPOS2                1042
#define IDC_CHECK_SplitterWndHScroll    1043
#define IDC_RADIO_BACKUP_TYPE1          1044
#define IDC_RADIO_BACKUP_TYPE3          1045
#define IDC_RADIO_OUTPUTMARKED          1046
#define IDC_RADIO_ALLAREA               1047
#define IDC_RADIO_CARETTYPE1            1048
#define IDC_CHECK_LCPOS3                1049
#define IDC_RADIO_FUNCKEYWND_PLACE2     1050
#define IDC_CHECK_BACKUP_YEAR           1051
#define IDC_CHECK_ALT                   1052
#define IDC_CHECK_DispTabIcon           1053
#define IDC_CHECK_BACKUP_HOUR           1054
#define IDC_CHECK_BACKUP_MIN            1055
#define IDC_CHECK_BACKUP_SEC            1056
#define IDC_CHECK_BACKUPDIALOG          1057
#define IDC_CHECK_BACKUPFOLDER          1058
#define IDC_CHECK_UNDERLINE             1059
#define IDC_EDIT_INPUT1                 1060
#define IDC_EDIT_PROPERTY               1061
#define IDC_EDIT_BACKUPFOLDER           1062
#define IDC_EDIT_EXTHELP1               1063
#define IDC_EDIT_PLSQL_E1               1064
#define IDC_EDIT_BLOCKCOMMENT_FROM      1065
#define IDC_EDIT_TYPENAME               1066
#define IDC_BUTTON_BACKUP_FOLDER_REF    1067
#define IDC_BUTTON_REPALCE              1068
#define IDC_BUTTON_DELETE               1069
#define IDC_BUTTON_DELKEYWORD           1070
#define IDC_EDIT_EXTHTMLHELP            1071
#define IDC_EDIT_TFORM                  1072
#define IDC_EDIT_BLOCKCOMMENT_FROM2     1073
#define IDC_EDIT_FNAME_TO               1074
#define IDC_CHECK_BACKUP_MONTH          1075
#define IDC_BUTTON_INSERTSEPARATOR      1076
#define IDC_BUTTON_ZOOMUP               1077
#define IDC_EDIT_MIGEMO_DLL             1078
#define IDC_CHECK_BACKUP_DAY            1079
#define IDC_BUTTON_INSERTWRAP           1080
#define IDC_EDIT_MIGEMO_DICT            1081
#define IDC_CHECK_AUTOSAVE              1082
#define IDC_CHECK_BACKUP_DUSTBOX        1083
#define IDC_LIST_FL                     1084
#define IDC_CHECK_DispTOOLBAR           1085
#define IDC_EDIT_AUTOBACKUP_INTERVAL    1086
#define IDC_BUTTON_OPENHELP1            1087
#define IDC_BUTTON_OPENEXTHTMLHELP      1088
#define IDC_EDIT_REPEATEDSCROLLLINENUM  1089
#define IDC_BUTTON_KEYWORDHELPFONT      1090
#define IDC_BUTTON_HELP                 1091
#define IDC_BUTTON_OPENMDLL             1092
#define IDC_BUTTON_OPENMDICT            1093
//#define IDC_EDIT_TO                     1094
#define IDC_EDIT_BLOCKCOMMENT_TO        1095
#define IDC_EDIT_BLOCKCOMMENT_TO2       1096
#define IDC_EDIT_TYPEEXTS               1097
#define IDC_EDIT_MARGINTY               1098
#define IDC_EDIT_nRulerBottomSpace      1099
#define IDC_EDIT_LINECOMMENT            1100
#define IDC_EDIT_INDENTCHARS            1101
#define IDC_EDIT_MAX_MRU_FOLDER         1102
#define IDC_EDIT_MARGINBY               1103
#define IDC_EDIT_nLineNumberRightSpace  1104
#define IDC_EDIT_LINECOMMENT2           1105
#define IDC_EDIT_MARGINLX               1106
#define IDC_LIST_FUNC                   1107
#define IDC_EDIT_MARGINRX               1108
#define IDC_COMBO_FUNCKIND              1109
#define IDC_EDIT_DANSPACE               1110
#define IDC_EDIT_LINECOMMENT3           1111
#define IDC_LIST_KEY                    1112
#define IDC_CHECK_CTRL                  1113
#define IDC_CHECK_ADDCRLFWHENCOPY       1114
#define IDC_COMBO_FILE                  1115
#define IDC_COMBO_nSortType             1116
#define IDC_COMBO_FOLDER                1117
#define IDC_STATIC_STC32                1118
#define IDC_COMBO_SETTINGNAME           1119
#define IDC_COMBO_PAPER                 1120
#define IDC_BUTTON_FOLDER               1121
#define IDC_CHK_SUBFOLDER               1122
#define IDC_STATIC_CURPATH              1123
#define IDC_CHK_DEFAULTFOLDER           1124
#define IDC_STATIC_HITCOUNT             1125
#define IDC_EDIT_VER                    1126
#define IDC_LIST_ASSIGNEDKEYS           1127
#define IDC_STATIC_MSG                  1128
#define IDC_RADIO_OUTPUTLINE            1129
#define IDC_RADIO_SELECTEDAREA          1130
#define IDC_BUTTON_REPALCEALL           1131
#define IDC_BUTTON_SEARCHPREV           1132
#define IDC_CHECK_CONSECUTIVEALL        1133
#define IDC_BUTTON_SEARCHNEXT           1134
#define IDC_LIST_RES                    1135
#define IDC_BUTTON_SETMARK              1136
#define IDC_TREE_FL                     1137
#define IDC_BUTTON_ADD                  1138
#define IDC_BUTTON_INSERT               1139
#define IDC_BUTTON_REGEX_INS            1140
#define IDC_BUTTON_UP                   1141
#define IDC_BUTTON_DOWN                 1142
#define IDC_BUTTON_SAMEBKCOLOR          1143
#define IDC_CHECK_REPEATEDSCROLLSMOOTH  1144
#define IDC_BUTTON_SAMETEXTCOLOR        1145
#define IDC_COMBO_CODE                  1146
#define IDC_RADIO_CARETTYPE0            1147
#define IDC_COMBO_EOL                   1148
#define IDC_BUTTON_COPY                 1149
#define IDC_COMBO_STRINGLITERAL         1150
#define IDC_CHECK_STRINGLINEONLY        1151
#define IDC_LIST_TYPES                  1152
#define IDC_RADIO_OUTPUTSTYLE1          1153
#define IDC_COMBO_PLSQLBLOCKS           1154
#define IDC_COMBO_MRU                   1155
#define IDC_CHECK_KEYWORDCASE           1156
#define IDC_COMBO_OPENFOLDER            1157
#define IDC_BUTTON_ADDKEYWORD           1158
#define IDC_BUTTON_IMPORT               1159
#define IDC_BUTTON_EXPORT               1160
#define IDC_BUTTON_ADDSET               1161
#define IDC_BUTTON_EDITKEYWORD          1162
#define IDC_BUTTON_DELSET               1163
#define IDC_COMBO_SET                   1164
#define IDC_LIST_KEYWORD                1165
#define IDC_SPIN_MAX_MRU_FILE           1166
#define IDC_SPIN_MAX_MRU_FOLDER         1167
#define IDC_SPIN_nDropFileNumMax        1168
#define IDC_SPIN_nRulerBottomSpace      1169
#define IDC_EDIT_MAX_MRU_FILE           1170
#define IDC_SPIN_PLSQL_E1               1171
#define IDC_SPIN_LCColNum2              1172
#define IDC_SPIN_nLineNumberRightSpace  1173
#define IDC_BUTTON_CLEAR_MRU_FILE       1174
#define IDC_SPIN_LCColNum3              1175
#define IDC_COMBO_MENU                  1176
#define IDC_RADIO_FUNCKEYWND_PLACE1     1177
#define IDC_CHECK_DispFUNCKEYWND        1178
#define IDC_CHECK_NOTIFYNOTFOUND        1179
#define IDC_EDIT_MIDASHIKIGOU           1180
#define IDC_EDIT_INYOUKIGOU             1181
#define IDC_PROGRESS_REPLACE            1182
#define IDC_STATIC_KENSUU               1183
#define IDC_STATIC_MYICON               1184
#define IDC_EDIT_HOKANFILE              1185
#define IDC_BUTTON_HOKANFILE_REF        1186
#define IDC_COMBO_HOKAN_TYPE            1187
#define IDC_LIST_COLORS                 1188
#define IDC_CHECK_DISP                  1189
#define IDC_CHECK_BOLD                  1190
#define IDC_RADIO_LINENUM_LAYOUT        1191
#define IDC_RADIO_LINENUM_CRLF          1192
#define IDC_STATIC_HAIKEI               1193
#define IDC_COMBO_CHARSET               1194
#define IDC_RADIO_LINETERMTYPE2         1195
#define IDC_EDIT_LINETERMCHAR           1196
#define IDC_RADIO_LINETERMTYPE0         1197
#define IDC_RADIO_LINETERMTYPE1         1198
#define IDC_LIST_FILES                  1199
#define IDC_STATIC_COMPARESRC           1200
#define IDC_CHECK_HOKANLOHICASE         1201
#define IDC_BUTTON_NEXTPAGE             1202
#define IDC_BUTTON_ZOOMDOWN             1203
#define IDC_BUTTON_PRINTSETTING         1204
#define IDC_EDIT_LINECOMMENTPOS         1205
#define IDC_BUTTON_PREVPAGE             1206
#define IDC_EDIT_LINECOMMENTPOS2        1207
#define IDC_SPIN_MARGINTY               1208
#define IDC_EDIT_LINECOMMENTPOS3        1209
#define IDC_SPIN_MARGINBY               1210
#define IDC_SPIN_MARGINLX               1211
#define IDC_SPIN_MARGINRX               1212
#define IDC_SPIN_FONTHEIGHT             1213
#define IDC_SPIN_DANSUU                 1214
#define IDC_EDIT_FOOT1                  1215
#define IDC_COMBO_FONT_HAN              1216
#define IDC_COMBO_FONT_ZEN              1217
#define IDC_SPIN_DANSPACE               1218
#define IDC_EDIT_FONTHEIGHT             1219
#define IDC_EDIT_DANSUU                 1220
#define IDC_CHECK_WORDWRAP              1221
#define IDC_CHECK_LINENUMBER            1222
#define IDC_CHECK_KINSOKUHEAD           1223
#define IDC_BUTTON_EDITSETTINGNAME      1224
#define IDC_CHECK_KINSOKUTAIL           1225
#define IDC_STATIC_PAGENUM              1226
#define IDC_CHECK_PS_KINSOKUHEAD        1227
#define IDC_CHECK_KINSOKURET            1228
#define IDC_STATIC_ZOOM                 1229
#define IDC_CHECK_PS_KINSOKUTAIL        1230
#define IDC_CHECK_KINSOKUKUTO           1231
#define IDC_CHECK_PS_KINSOKURET         1232
#define IDC_CHECK_PS_KINSOKUKUTO        1233
#define IDC_EDIT_HEAD1                  1234
#define IDC_STATIC_PRNDEV               1235
#define IDC_STATIC_PAPER                1236
#define IDC_EDIT_KEYSFUNC               1237
#define IDC_BUTTON_ASSIGN               1238
#define IDC_EDIT_HEAD2                  1239
#define IDC_EDIT_HEAD3                  1240
#define IDC_BUTTON_CURRENTFOLDER        1241
//#define IDC_EDIT_DEBUG                  1242
#define IDC_EDIT_FOOT2                  1243
#define IDC_CHECK_USETRAYICON           1244
#define IDC_EDIT_FOOT3                  1245
#define IDC_CHECK_STAYTASKTRAY          1246
#define IDC_CHECK_DispSTATUSBAR         1247
#define IDC_RADIO_OUTPUTSTYLE2          1248
#define IDC_CHECK_DispTabWnd            1249
#define IDC_STATIC_ENABLECOLUMNS        1250
#define IDC_STATIC_ENABLELINES          1251
#define IDC_HOTKEY_TRAYMENU             1252
#define IDC_CHECK_ENABLEUNMODIFIEDOVERWRITE 1253
#define IDC_CHECK_DRAGDROP              1254
#define IDC_CHECK_DROPSOURCE            1255
#define IDC_CHECK_COPYnDISABLESELECTEDAREA 1256
#define IDC_CHECK_HTMLHELPISSINGLE      1257
#define IDC_CHECK_bEnableLineModePaste  1258
#define IDC_CHECK_bSelectClickedURL     1259
#define IDC_EDIT_nRulerHeight           1260
#define IDC_CHECK_bEnableNoSelectCopy   1261
#define IDC_CHECK_bGrepExitConfirm      1262
#define IDC_CHECK_TILE_H                1263
#define IDC_CHECK_bDropFileAndClose     1264
#define IDC_EDIT_nDropFileNumMax        1265
#define IDC_CHECK_bCheckFileTimeStamp   1266
#define IDC_CHECK_bNotOverWriteCRLF     1267
#define IDC_COMBO_OUTLINES              1268
#define IDC_COMBO_SMARTINDENT           1269
#define IDC_BUTTON_REFERENCE            1270
#define IDC_COMBO_IMESTATE              1271
#define IDC_CHECK_bAutoCloseDlgFind     1272
#define IDC_COMBO_IMESWITCH             1273
#define IDC_CHECK_bScrollBarHorz        1274
#define IDC_CHECK_bAutoCloseDlgFuncList 1275
#define IDC_CHECK_bAutoCloseDlgReplace  1276
#define IDC_CHECK_bMarkUpBlankLineEnable 1277
#define IDC_CHECK_bFunclistSetFocusOnJump 1278
#define IDC_STATIC_CURFILE              1279
#define IDC_PROGRESS                    1280
#define IDC_LIST_WORDS                  1281
#define IDC_CHECK_m_bHokanKey_RETURN    1282
#define IDC_CHECK_m_bHokanKey_TAB       1283
#define IDC_CHECK_m_bHokanKey_RIGHT     1284
#define IDC_RADIO_DFORM_0               1285
#define IDC_RADIO_DFORM_1               1286
#define IDC_EDIT_DFORM_EX               1287
#define IDC_RADIO_TFORM_0               1288
#define IDC_RADIO_TFORM_1               1289
#define IDC_EDIT_TFORM_EX               1290
#define IDC_EDIT_DFORM                  1291
//#define IDC_RADIO_ALL                   1292
#define IDC_RADIO_PORTRAIT              1293
#define IDC_RADIO_BACKUP_DATETYPE1      1294
#define IDC_RADIO_REPLACE               1295
#define IDC_RADIO_DIFF_FILE1            1296
#define IDC_RADIO_DIFF_FILE2            1297
#define IDC_RADIO_OUTLINEDEFAULT        1298
//#define IDC_RADIO_FROMTO                1299
#define IDC_RADIO_LANDSCAPE             1300
#define IDC_RADIO_BACKUP_DATETYPE2      1301
#define IDC_RADIO_INSERT                1302
#define IDC_RADIO_OUTLINERULEFILE       1303
#define IDC_RADIO_ADD                   1304
#define IDC_RADIO_DIFF_DST1             1305
#define IDC_RADIO_DIFF_DST2             1306
#define IDC_EDIT_BACKUP_3               1307
#define IDC_MACROPATH                   1308
#define IDC_EDIT_TAG_MAKE_CMDLINE       1309
#define IDC_EDIT_WX                     1310
#define IDC_EDIT_VERTLINE               1311
#define IDC_COMBO_m_szCommand           1312
#define IDC_EDIT_WY                     1313
#define IDC_CHECK_GETSTDOUT             1314
#define IDC_EDIT_SX                     1315
#define IDC_STATIC_CMD                  1316
#define IDC_EDIT_SY                     1317
#define IDC_STATIC_JOBNAME              1318
#define IDC_STATIC_PROGRESS             1319
//#define IDC_EDIT_FROM                   1320
//#define IDC_STATIC_ALL                  1321
#define IDC_CHECK_bMenuIcon             1322
#define IDC_LABEL_BACKUP_3              1323
#define IDC_LABEL_BACKUP_4              1324
#define IDC_LABEL_AUTOSAVE              1325
#define IDC_LABEL_AUTOSAVE2             1326
#define IDC_LABEL_AUTOSAVE3             1327
#define IDC_LABEL_AUTOSAVE4             1328
#define IDC_LABEL_MENUFUNC              1329
#define IDC_LABEL_MENUFUNCKIND          1330
#define IDC_LABEL_MENU                  1331
#define IDC_LABEL_MENUCHOICE            1332
#define IDC_LABEL_MENUKEYCHANGE         1333
#define IDC_LABEL_TOOLBAR               1334
#define IDC_LABEL_MENUNAME              1335
#define IDC_LABEL_KEYKIND               1336
#define IDC_LABEL_FUNCtoKEY             1337
#define IDC_LABEL_KEYtoFUNC             1338
#define IDC_LABEL_LINETERMCHAR          1339
#define IDC_LABEL_DFORM                 1340
#define IDC_LABEL_TFORM                 1341
//#define IDC_LABEL_FROM                  1342
//#define IDC_LABEL_TO                    1343
#define IDC_LABEL_PLSQL1                1344
#define IDC_LABEL_PLSQL2                1345
#define IDC_LABEL_PLSQL3                1346
#define IDC_SPIN_BACKUP_GENS            1347
#define IDC_SPIN_AUTOBACKUP_INTERVAL    1348
#define IDC_SPIN_nRulerHeight           1349
#define IDC_CHECK_BACKUP_RETAINEXT      1350
#define IDC_SPIN_LINENUM                1351
#define IDC_LANEL_NOTE                  1352
#define IDC_CHECK_RestoreCurPosition    1353
#define IDC_STATIC_URL_CAPTION          1354
#define IDC_STATIC_URL_UR               1355
#define IDC_CHECK_AutoMIMEDecode        1356
#define IDC_EDIT_MENUNAME               1357
#define IDC_CHECK_RestoreBookmarks      1358
#define IDC_BUTTON_TEMPCHANGE           1359
#define IDC_STATIC_EOL                  1360
#define IDC_BUTTON_JUMP                 1361
#define IDC_CHECK_LCPOS                 1362
#define IDC_SPIN_LCColNum               1363
#define IDC_LABEL_LCPOS                 1364
#define IDC_LABEL_LCPOS2                1365
#define IDC_LABEL_LCPOS3                1366
#define IDC_MACRO_REG                   1367
#define IDC_COMBO_MACROID               1368
#define IDC_BUTTON_REGEX_TOP            1369
#define IDC_BUTTON_REGEX_LAST           1370
#define IDC_MACROLIST                   1371
#define IDC_MACRONAME                   1372
#define IDC_EDIT_ABOUT                  1373
#define IDC_CHECK_SplitterWndVScroll    1374
#define IDC_BUTTON_REGEX_UPD            1375
#define IDC_CHK_WORD                    1376
#define IDC_BUTTON_REGEX_DEL            1377
#define IDC_CHECK_SameTabWidth          1378
#define IDC_MACRODIR                    1379
#define IDC_MACRODIRREF                 1380
#define IDC_BUTTON_MENUNAME             1381
#define IDC_EDIT_REGEX                  1382
#define IDC_CHECK_REGEX                 1383
#define IDC_LIST_REGEX                  1384
#define IDC_COMBO_REGEX_COLOR           1385
#define IDC_LABEL_REGEX_COLOR           1386
#define IDC_LABEL_REGEX_KEYWORD         1387
#define IDC_BUTTON_REGEX_UP             1388
#define IDC_BUTTON_REGEX_DOWN           1389
#define IDC_BUTTON_REGEX_ADD            1390
#define IDC_BUTTON_REGEX_IMPORT         1391
#define IDC_BUTTON_REGEX_EXPORT         1392
#define IDC_FRAME_REGEX                 1393
#define IDC_LABEL_REGEX_VERSION         1394
#define IDC_CHECK_INS_SPACE             1395
#define IDC_CHK_PASTE                   1396
#define IDC_CHECK_SEARCHALL             1397
#define IDC_EDIT_TYPEEXTHELP            1398
#define IDC_EDIT_TYPEEXTHTMLHELP        1399
#define IDC_BUTTON_TYPEOPENHELP         1400
#define IDC_BUTTON_TYPEOPENEXTHTMLHELP  1401
#define IDC_CHECK_TYPEHTMLHELPISSINGLE  1402
#define IDC_CHECK_DispTabWndMultiWin    1403
#define IDC_EDIT_OUTLINERULEFILE        1404
#define IDC_BUTTON_RULEFILE_REF         1405
#define IDC_EDIT_KINSOKUHEAD            1406
#define IDC_STATIC_DIFF_SRC             1407
#define IDC_EDIT_KINSOKUTAIL            1408
#define IDC_EDIT_DIFF_DST               1409
#define IDC_BUTTON_DIFF_DST             1410
#define IDC_SPIN_FUNCKEYWND_GROUPNUM    1411
#define IDC_CHECK_DIFF_OPT_CASE         1412
#define IDC_EDIT_FUNCKEYWND_GROUPNUM    1413
#define IDC_CHECK_DIFF_OPT_SPACE        1414
#define IDC_CHECK_DIFF_OPT_SPCCHG       1415
#define IDC_STATIC_nSortType            1416
#define IDC_BTN_RELOAD                  1417
#define IDC_CHECK_DIFF_OPT_BLINE        1418
#define IDC_CHECK_DIFF_OPT_TABSPC       1419
#define IDC_BTN_NOTIFYONLY              1420
#define IDC_FRAME_DIFF_FILE12           1421
#define IDC_LIST_DIFF_FILES             1422
#define IDC_FILEUPDATEMSG               1423
#define IDC_FRAME_DIFF_DST              1424
#define IDC_LIST_CTRLCODE               1425
#define IDC_BTN_NOSUPERVISION           1426
#define IDC_BTN_CLOSE                   1427
#define IDC_UPDATEDFILENAME             1428
#define IDC_QUERYRELOADMSG              1429
#define IDC_BUTTON_FNAME_TOP            1430
#define IDC_BUTTON_FNAME_UP             1431
#define IDC_BUTTON_FNAME_DOWN           1432
#define IDC_BUTTON_FNAME_LAST           1433
#define IDC_BUTTON_FNAME_INS            1434
#define IDC_BUTTON_FNAME_ADD            1435
#define IDC_BUTTON_FNAME_UPD            1436
#define IDC_BUTTON_FNAME_DEL            1437
#define IDC_LIST_FNAME                  1438
#define IDC_EDIT_FNAME_FROM             1439
#define IDC_CHECK_TAB_ARROW             1440
#define IDC_TAB_FAVORITE                1441
#define IDC_LIST_FAVORITE_FILE          1442
#define IDC_LIST_FAVORITE_FOLDER        1443
#define IDC_LIST_FAVORITE_GREP_FILE     1444
#define IDC_LIST_FAVORITE_GREP_FOLDER   1445
#define IDC_LIST_FAVORITE_REPLACE       1446
#define IDC_LIST_FAVORITE_SEARCH        1447
#define IDC_LIST_FAVORITE_CMD           1448
#define IDC_BUTTON_CLEAR                1449
#define IDC_LIST_TAGJUMP                1450
#define IDC_WINCAPTION_ACTIVE           1451
#define IDC_WINCAPTION_INACTIVE         1452
#define IDC_CHECK_HOKANBYFILE           1453
#define IDC_BUTTON_TAG_MAKE_REF         1454
#define IDC_TABWND_CAPTION              1455
#define IDC_CHECK_TAG_MAKE_RECURSE      1456
#define IDC_EDIT_TAG_MAKE_FOLDER        1457
#define IDC_FRAME_SEARCH_MSG            1458
#define IDC_CHECK_DIFF_EXEC_STATE       1459
#define IDC_STATIC_FAVORITE_MSG         1460
#define IDC_CHECK_REALTIMEVIEW          1461
#define IDC_CHECK_BOM                   1462
#define IDC_CHECK_GREPREALTIME          1463
#define IDC_RADIO_WINSIZE_DEF           1464
#define IDC_RADIO_WINSIZE_SAVE          1465
#define IDC_RADIO_WINSIZE_SET           1466
#define IDC_SPIN_WX                     1467
#define IDC_SPIN_WY                     1468
#define IDC_RADIO_WINPOS_DEF            1469
#define IDC_RADIO_WINPOS_SAVE           1470
#define IDC_RADIO_WINPOS_SET            1471
#define IDC_SPIN_SX                     1472
#define IDC_SPIN_SY                     1473
#define IDC_COMBO_WINTYPE               1474
#define IDC_BUTTON_WINSIZE              1475
#define IDC_CHECK_QueryIfCodeChange     1476
#define IDC_CHECK_AlertIfFileNotExist   1477
#define IDC_COMBO1                      1478
#define IDC_COMBO2                      1479
#define IDC_COMBO3                      1480
#define IDC_COMBO4                      1481
#define IDC_COMBO5                      1482
#define IDC_COMBO6                      1483
#define IDC_COMBO7                      1484
#define IDC_COMBO8                      1485
#define IDC_COMBO9                      1486
#define IDC_COMBO10                     1487
#define IDC_BUTTON_KEYWORD_SELECT       1488
#define IDC_STATIC_KEYWORD_COUNT        1489
#define IDC_BUTTON_KEYSETRENAME         1490
#define IDC_BUTTON_KEYCLEAN             1491
#define IDC_KEYWORD                     1492
#define IDC_STATIC_KEYWORD              1493
#define IDC_CHECK_ICASE                 1494
#define IDC_CHECK_ANYWHERE              1495
#define IDC_EDIT_BACKUPFILE             1496
#define IDC_CHECK_BACKUP_FOLDER_RM      1497
#define IDC_CHECK_BACKUP_ADVANCED       1498
#define IDC_RADIO_BACKUP_DATETYPE1A     1499
#define IDC_RADIO_BACKUP_DATETYPE2A     1500
#define IDC_LABEL_BACKUP_HELP2          1501
#define IDC_CHECK_MEMDC                 1502
#define IDC_STATIC_COLOR                1503
#define IDC_BUTTON_SELALL               1504
#define IDC_BUTTON_SELNOTING            1505
#define IDC_LIST_ITEMINFO               1506
#define IDC_CHECK_NoFilterSaveNew       1507
#define IDC_CHECK_NoFilterSaveFile      1508
#define IDC_CHECK_CLOSEALLCONFIRM       1509
#define IDC_CHECK_ANTIALIAS             1510
#define IDC_CHECK_RetainEmptyWindow     1511
#define IDC_BUTTON_DIRECTPAGE           1512
#define IDC_CHECK_CloseOneWin           1513
#define IDC_CHECK_bCaretTextForSearch   1514
#define IDC_CHECK_ChgWndByWheel         1515
#define IDC_LABEL_REGEXP                1516
#define IDC_EDIT_REGEXPLIB              1517
#define IDC_LABEL_REGEXP_VER            1518
#define IDC_COMBO_CODE_GET              1519
#define IDC_COMBO_CODE_SEND             1520
#define IDC_CHECK_DISP_UNICODE_IN_SJIS  1521
#define IDC_CHECK_DISP_UNICODE_IN_JIS   1522
#define IDC_CHECK_DISP_UNICODE_IN_EUC   1523
#define IDC_CHECK_DISP_UTF8_CODEPOINT   1524
#define IDC_CHECK_DISP_SP_CODEPOINT     1525
#define IDC_RADIO_OUTPUT                1526
#define IDC_RADIO_EDITWINDOW            1527
#define IDC_CHECK_SENDSTDIN             1528
#define IDC_CHECK_SortTabList           1529
#define IDC_COMBO_WRAPMETHOD            1530
#define IDC_FRAME_KEYHELP               1531
#define IDC_LIST_KEYHELP                1532
#define IDC_LABEL_KEYHELP_KEYWORD       1533
#define IDC_EDIT_KEYHELP                1534
#define IDC_LABEL_KEYHELP_TITLE         1535
#define IDC_BUTTON_KEYHELP_INS          1536
#define IDC_BUTTON_KEYHELP_UPD          1537
#define IDC_BUTTON_KEYHELP_DEL          1538
#define IDC_BUTTON_KEYHELP_TOP          1539
#define IDC_BUTTON_KEYHELP_UP           1540
#define IDC_BUTTON_KEYHELP_DOWN         1541
#define IDC_BUTTON_KEYHELP_LAST         1542
#define IDC_BUTTON_KEYHELP_IMPORT       1543
#define IDC_BUTTON_KEYHELP_EXPORT       1544
#define IDC_LABEL_KEYHELP_ABOUT         1545
#define IDC_CHECK_KEYHELP               1546
#define IDC_LABEL_KEYHELP_PRIOR         1547
#define IDC_BUTTON_KEYHELP_REF          1548
#define IDC_CHECK_KEYHELP_ALLSEARCH     1549
#define IDC_CHECK_KEYHELP_KEYDISP       1550
#define IDC_CHECK_KEYHELP_PREFIX        1551
#define IDC_SPIN_ALERT_FILESIZE         1552
#define IDC_EDIT_ALERT_FILESIZE         1553
#define IDC_CHECK_ALERT_IF_LARGEFILE    1554
#define IDC_COMBO_WHEEL_HSCROLL         1555
#define IDC_COMBO_WHEEL_PAGESCROLL      1556
#define IDC_COMBO_DEFAULT_CODETYPE      1557
#define IDC_CHECK_PRIOR_CESU8           1558
#define IDC_CHECK_DISP_SELCOUNT_BY_BYTE 1559
#define IDC_EDIT_KINSOKUKUTO            1560
//#define IDC_CHECK_ACCELTBL_EACHWIN      1561
#define IDC_CHECK_MacroOnOpened         1562
#define IDC_CHECK_MacroOnTypeChanged    1563
#define IDC_CHECK_MacroOnSave           1564
#define IDC_PLUGINLIST                  1565
#define IDC_CHECK_PluginEnable          1566
#define IDC_PLUGIN_SearchNew            1567
#define IDC_PLUGIN_Remove               1568
#define IDC_LABEL_PLUGIN_Description    1569
#define IDC_LABEL_PLUGIN_Author         1570
#define IDC_LABEL_PLUGIN_Version        1571
#define IDC_PLUGIN_OPTION               1572
#define IDC_LIST_PLUGIN_OPTIONS         1573
#define IDC_EDIT_PLUGIN_OPTION          1574
#define IDC_EDIT_PLUGIN_OPTION_NUM      1575
#define IDC_SPIN_PLUGIN_OPTION          1576
#define IDC_CHECK_PLUGIN_OPTION         1577
#define IDC_COMBO_PLUGIN_OPTION         1578
#define IDC_BUTTON_INITIALIZE           1578
#define IDC_RADIO_TYPE_TO               1579
#define IDC_STATIC_TYPE_FILE            1580
#define IDC_COMBO_COLORS                1581
#define IDC_BUTTON_MENU                 1582
#define IDC_STATIC_BUTTONS              1582
#define IDC_BUTTON_DELETE_NOFAVORATE    1583
#define IDC_BUTTON_DELETE_NOTFOUND      1584
#define IDC_BUTTON_DELETE_SELECTED      1585
#define IDC_BUTTON_PREVTAG              1586
#define IDC_BUTTON_NEXTTAG              1587
#define IDC_STATIC_BASEDIR              1588
#define IDC_TREE_RES                    1589
#define IDC_BUTTON_INSERT_NODE          1590
#define IDC_BUTTON_INSERT_A             1591
#define IDC_BUTTON_RIGHT                1592
#define IDC_BUTTON_LEFT                 1593
#define IDC_CHECK_KEY_PARENTHESES       1594
#define IDC_BUTTON_EXPAND               1595
#define IDC_BUTTON_COLLAPSE             1596
#define IDC_BUTTON_CHECK                1597
#define IDC_CHECK_EXT_RMENU             1598
#define IDC_CHECK_EXT_DBLCLICK          1599
#define IDC_COMBO_DEFAULT_EOLTYPE       1600
#define IDC_CHECK_DEFAULT_BOM           1601
#define IDC_EDIT_BACKIMG_PATH           1602
#define IDC_BUTTON_BACKIMG_PATH_SEL     1603
#define IDC_COMBO_BACKIMG_POS           1604
#define IDC_CHECK_BACKIMG_SCR_X         1605
#define IDC_CHECK_BACKIMG_SCR_Y         1606
#define IDC_CHECK_BACKIMG_REP_X         1607
#define IDC_CHECK_BACKIMG_REP_Y         1608
#define IDC_EDIT_BACKIMG_OFFSET_X       1609
#define IDC_EDIT_BACKIMG_OFFSET_Y       1610
#define IDC_CHECK_CONVERTEOLPASTE       1611
#define IDC_CHECK_OpenNewWin            1612
#define IDC_BUTTON_TABFONT              1613
#define IDC_MACROCANCELTIMER            1614
#define IDC_PLUGIN_OpenFolder           1615
#define IDC_CHECK_INHERIT_KEY_OTHER_VIEW 1616
#define IDC_LIST_FAVORITE_EXCEPTMRU     1617
#define IDC_BUTTON_ADD_FAVORITE         1618
#define IDC_BTN_AUTOLOAD                1619
#define IDC_LABEL_AUTOLOAD_DELAY        1620
#define IDC_EDIT_AUTOLOAD_DELAY         1621
#define IDC_SPIN_AUTOLOAD_DELAY         1622
#define IDC_CHECK_KINSOKUHIDE           1623
#define IDC_PLUGIN_README               1624
#define IDC_PLUGIN_INST_ZIP             1625
#define IDC_CHECK_HOKANBYKEYWORD        1626
#define IDC_RADIO_CURDIR                1627
#define IDC_RADIO_MRUDIR                1628
#define IDC_RADIO_SELDIR                1629
#define IDC_EDIT_FILEOPENDIR            1630
#define IDC_BUTTON_FILEOPENDIR          1631
#define IDC_CHECK_bOverWriteFixMode     1632
#define IDC_STATIC_MOZI                 1633
#define IDC_BUTTON_TYPEFONT             1634
#define IDC_CHECK_USETYPEFONT           1635
#define IDC_STATIC_TABFONT              1636
#define IDC_STATIC_KEYWORDHELPFONT      1637
#define IDC_STATIC_FONTSIZE             1638
#define IDC_CHECK_COLORPRINT            1639
#define IDC_CHECK_USE_FONT_HEAD         1640
#define IDC_BUTTON_FONT_HEAD            1641
#define IDC_STATIC_FONT_HEAD            1642
#define IDC_CHECK_USE_FONT_FOOT         1643
#define IDC_BUTTON_FONT_FOOT            1644
#define IDC_STATIC_FONT_FOOT            1645
#define IDC_CHECK_CUR_DIR               1646
#define IDC_COMBO_CUR_DIR               1647
#define IDC_BUTTON_REFERENCE2           1648
#define IDC_LIST_FAVORITE_CUR_DIR       1649
#define IDC_EDIT_PLUGIN_OPTION_DIR      1650
#define IDC_BUTTON_PLUGIN_OPTION_DIR    1651
#define IDC_CHECK_STRINGENDLINE         1652
#define IDC_CHECK_DispTabClose          1653
#define IDC_CHECK_CHKENTERATEND         1654
#define IDC_RADIO_OUTPUTSTYLE3          1655
#define IDC_CHECK_FILE_ONLY             1656
#define IDC_CHECK_BASE_PATH             1657
#define IDC_CHECK_SEP_FOLDER            1658
#define IDC_BUTTON_FOLDER_UP            1659
#define IDC_CHECK_SUBMENU               1660
#define IDC_COMBO_LANGUAGE              1661
#define IDC_BUTTON_UP_TYPE              1662
#define IDC_BUTTON_DOWN_TYPE            1663
#define IDC_BUTTON_ADD_TYPE             1664
#define IDC_BUTTON_DEL_TYPE             1665
#define IDC_BUTTON_COPY_TYPE            1666
#define IDC_RADIO_TYPE_ADD              1667
#define IDC_STATIC_TYPEFONT             1668
#define IDC_TextTabClose                1669
#define IDC_TextTabCaption              1670
#define IDC_CHECK_CP                    1671
#define IDC_CHECK_ENABLEEXTEOL          1672
#define IDC_LIST_PROFILE                1673
#define IDC_BUTTON_PROF_CREATE          1674
#define IDC_BUTTON_PROF_RENAME          1675
#define IDC_BUTTON_PROF_DELETE          1676
#define IDC_CHECK_PROF_DEFSTART         1677
#define IDC_BUTTON_PROF_DEFSET          1678
#define IDC_BUTTON_PROF_DEFCLEAR        1679
#define IDC_TAB_POSITION                1680
#define IDC_COMBO_TAB_POSITION          1681
#define IDC_CHECK_TAB_MULTILINE         1682
#define IDC_CHECK_bOverWriteBoxDelete   1683
#define IDC_CHECK_SHORTPATH             1684
#define IDC_EDIT_SHORTMAXWIDTH          1685
#define IDC_COMBO_TAGJUMP               1686
#define IDC_COMBO_KEYWORD_TAGJUMP       1687
#define IDC_SPIN_LINENUMWIDTH           1688
#define IDC_EDIT_LINENUMWIDTH           1689
#define IDC_CHK_BACKUP                  1690
#define IDC_STATIC_SETTFING_FROM        1691
#define IDC_CHECK_LOADINI               1692
#define IDC_EDIT_DEFINI                 1693
#define IDC_BUTTON_REF1                 1694
#define IDC_BUTTON_LOAD                 1695
#define IDC_RADIO_GREP                  1696
#define IDC_RADIO_FILE                  1697
#define IDC_RADIO_FOLDER                1698
#define IDC_STATIC_PATH                 1699
#define IDC_EDIT_PATH                   1700
#define IDC_BUTTON_REF2                 1701
#define IDC_BUTTON_PATH_MENU            1702
#define IDC_EDIT_LABEL                  1703
#define IDC_STATIC_FILE                 1704
#define IDC_EDIT_FILE                   1705
#define IDC_CHECK_HIDDEN                1706
#define IDC_CHECK_READONLY              1707
#define IDC_CHECK_SYSTEM                1708
#define IDC_BUTTON_UPDATE               1709
#define IDC_BUTTON_FILEADD              1710
#define IDC_BUTTON_REPLACE              1711
#define IDC_BUTTON_SETTING              1712
#define IDC_STATIC_CHARCODE             1713
#define IDC_PLUGIN_URL                  1714
#define IDC_RADIO_LINEDELETE            1715
#define IDC_RADIO_NOHIT                 1716
#define IDC_CHECK_BOXSELECTLOCK         1717
#define IDC_COMBO_TSV_MODE              1718
#define IDC_CHECK_INDENTCPPSTR          1719
#define IDC_CHECK_INDENTCPPCMT          1720
#define IDC_CHECK_INDENTCPPUNDO         1721
#define IDC_CHECK_DISP_COL_BY_CHAR      1722
#define IDC_STATIC_MENU                 1723
#define IDC_LIST_WINDOW                 1724
#define IDC_BUTTON_SAVE                 1725
#define IDC_BUTTON_CLOSE                1726
#define IDC_STATIC_URL_GIT              1727
#define IDC_STATIC_GIT_CAPTION          1728
#define IDC_STATIC_URL_APPVEYOR_CAPTION 1729
#define IDC_STATIC_URL_APPVEYOR_BUILD   1730
#define IDC_STATIC_URL_GITHUB_CAPTION   1731
#define IDC_STATIC_URL_GITHUB_COMMIT    1732
#define IDC_STATIC_URL_GITHUB_PR        1733
#define IDS_AUTHOR_PAGE                 4054
#define IDS_ABOUT_DESCRIPTION           4056
#define IDD_TYPELIST                    5000
#define IDD_TYPE_ASCERTAIN              5001
#define IDD_PROP_SCREEN                 5100
#define IDD_PROP_COLOR                  5101
#define IDD_PROP_SUPPORT                5102
#define IDD_PROP_REGEX                  5103
#define IDD_PROP_KEYHELP                5104
#define IDD_PROP_WINDOW                 5105
#define IDD_DIALOG_KEYWORD_SELECT       5110
#define IDD_SAMECOLOR                   5111
#define IDD_PROP_GENERAL                5200
#define IDD_PROP_WIN                    5201
#define IDD_PROP_TOOLBAR                5202
#define IDD_PROP_TAB                    5203
#define IDD_PROP_STATUSBAR              5204
#define IDD_PROP_EDIT                   5205
#define IDD_PROP_FILE                   5206
#define IDD_PROP_FNAME                  5207
#define IDD_PROP_BACKUP                 5208
#define IDD_PROP_FORMAT                 5209
#define IDD_PROP_GREP                   5210
#define IDD_PROP_KEYBIND                5211
#define IDD_PROP_CUSTMENU               5212
#define IDD_PROP_KEYWORD                5213
#define IDD_PROP_HELPER                 5214
#define IDD_PROP_MACRO                  5215
#define IDD_PROP_PLUGIN                 5216
#define IDD_PROP_MAINMENU               5217
#define IDD_WINPOSSIZE                  5220
#define IDD_PLUGIN_OPTION               5221
#define IDD_PROFILEMGR                  5222
#define IDD_FILETREE                    5223
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        230
#define _APS_NEXT_COMMAND_VALUE         4057
#define _APS_NEXT_CONTROL_VALUE         1734
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
