name: Check Encoding

on:
  push:
    paths-ignore:
      - '**/*.md'
      - '.gitignore'
      - '.editorconfig'
  pull_request:
    paths-ignore:
      - '**/*.md'
      - '.gitignore'
      - '.editorconfig'
  workflow_dispatch:

jobs:
  check-encoding:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd # 指定しない限りcmdを使う
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0  # 過去の履歴も含めて全て取得 (check_encoding.py で origin/master にアクセスするため)

      - name: Show environment variables for debug
        run: set

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ vars.PYTHON_VERSION || '3.14.3' }}
          cache: 'pip'
      - run: pip install -r requirements.txt

      - name: Python version check
        run: python --version

      - name: Check encoding
        run: checkEncoding.bat
