name: Doxygen

on:
  push:
    paths-ignore:
      - '**/*.md'
      - '.gitignore'
      - '.editorconfig'
  pull_request:
    paths-ignore:
      - '**/*.md'
      - '.gitignore'
      - '.editorconfig'
  workflow_dispatch:

jobs:
  doxygen:
    runs-on: windows-latest
    strategy:
      matrix:
        BuildPlatform: [Win32]
        Configuration: [Release]
    env:
      BuildPlatform: ${{ matrix.BuildPlatform }}
      Configuration: ${{ matrix.Configuration }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Set up MSYS2
        uses: msys2/setup-msys2@66cd2cce69caa17b53920067426061ca1de3a884 # v2.32.0
        with:
          msystem: MINGW64
          update: true
          install: >-
            doxygen

      - name: Show environment variables for debug
        run: set
        shell: cmd

      - name: Run doxygen
        run: ./run-doxygen.bat ${{ env.BuildPlatform }} ${{ env.Configuration }}
        shell: msys2 {0}

      - name: Zip files for artifacts
        run: zipArtifacts.bat ${{ env.BuildPlatform }} ${{ env.Configuration }}
        shell: cmd

      - name: Upload doxygen artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: doxygen_${{ env.BuildPlatform }}_${{ env.Configuration }}
          path: '**Dev.zip'